account/urls.py
from django.conf.urls import include, re_path, url
from django.conf import settings

from .views import profile, newapikey, deleteapikey, RatticSessionDeleteView
from .views import RatticTFADisableView, RatticTFABackupTokensView
from .views import RatticTFASetupView, RatticTFALoginView
from .views import RatticTFAGenerateApiKey
from .views import RatticChangePasswordView
from .views import ldap_password_change
from django.contrib import auth as dj_auth

from two_factor.views import QRGeneratorView

app_name='account'

urlpatterns = [
    re_path(r'^$', profile, {}, name='profile'),
    re_path(r'^newapikey/$', newapikey, {}, name="newapikey"),
    re_path(r'^deleteapikey/(?P<key_id>\d+)/$', deleteapikey, {}, name="deleteapikey"),

    re_path(r'^logout/$', dj_auth.views.LogoutView.as_view(), name='logout'),

    # View to kill other sessions with
    re_path(r'^killsession/(?P<pk>\w+)/', RatticSessionDeleteView.as_view(), name='kill_session'),

    # Two Factor Views
    re_path(r'^login/$', RatticTFALoginView.as_view(), name='login'),
    re_path(r'^generate_api_key$', RatticTFAGenerateApiKey.as_view(), name="generate_api_key"),

    re_path(r'^two_factor/disable/$', RatticTFADisableView.as_view(), name='tfa_disable'),
    re_path(r'^two_factor/backup/$', RatticTFABackupTokensView.as_view(), name='tfa_backup'),
    re_path(r'^two_factor/setup/$', RatticTFASetupView.as_view(), name='tfa_setup'),
    re_path(r'^two_factor/qr/$', QRGeneratorView.as_view(), name='tfa_qr'),
]

if settings.GOAUTH2_ENABLED:
    urlpatterns += [
        re_path(r'', include('social_auth.urls')),
    ]

# URLs we don't want enabled with LDAP
if not settings.LDAP_ENABLED:
    urlpatterns += [
        re_path(r'^reset/$', dj_auth.views.PasswordResetView.as_view(), {
                'post_reset_redirect': '/account/reset/done/',
                'template_name': 'password_reset.html'},
            name="password_reset"
        ),

        re_path(r'^reset/done/$', dj_auth.views.PasswordResetDoneView.as_view(), {
            'template_name': 'password_reset_done.html'},
            name="password_reset_done"
        ),

        re_path(r'^reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', dj_auth.views.PasswordResetConfirmView.as_view(), {
            'post_reset_redirect': '/',
            'template_name': 'password_reset_confirm.html'},
            name="password_reset_confirm"
        ),

        url(r'^changepass/$', RatticChangePasswordView.as_view(), {
            'post_change_redirect': '/account/',
            'template_name': 'account_changepass.html'}, name='password_change')
    ]

# URLs we do want enabled with LDAP
if settings.LDAP_ENABLED and settings.AUTH_LDAP_ALLOW_PASSWORD_CHANGE:
    urlpatterns += [
        re_path(r'^changepass/$', ldap_password_change, {}, name='password_change')
    ]

cred/urls.py
from django.conf.urls import re_path
from django.conf import settings
import cred.views as v

LOCAL_PREFIX = ""
app_name = 'cred'

urlpatterns = [
    # New list views
    re_path(r'^list/$', v.list, name="list"),
    re_path(r'^list-by-(?P<cfilter>\w+)/(?P<value>[^/]*)/$', v.list, name="list"),
    re_path(r'^list-by-(?P<cfilter>\w+)/(?P<value>[^/]*)/sort-(?P<sortdir>ascending|descending)-by-(?P<sort>\w+)/$', v.list, name="list"),
    re_path(r'^list-by-(?P<cfilter>\w+)/(?P<value>[^/]*)/sort-(?P<sortdir>ascending|descending)-by-(?P<sort>\w+)/page-(?P<page>\d+)/$', v.list, name="list"),

    # Search dialog for mobile
    re_path(r'^search/$', v.search, name='search'),

    # Single cred views
    re_path(r'^detail/(?P<cred_id>\d+)/$', v.detail, name="detail"),
    re_path(r'^detail/(?P<cred_id>\d+)/fingerprint/$', v.ssh_key_fingerprint, name="ssh_key_fingerprint"),
    re_path(r'^detail/(?P<cred_id>\d+)/download/$', v.downloadattachment, name="downloadattachment"),
    re_path(r'^detail/(?P<cred_id>\d+)/ssh_key/$', v.downloadsshkey, name="downloadsshkey"),
    re_path(r'^edit/(?P<cred_id>\d+)/$', v.edit, name='edit'),
    re_path(r'^delete/(?P<cred_id>\d+)/$', v.delete, name='delete'),
    re_path(r'^add/$', v.add, name="add"),

    # Adding to the change queue
    re_path(r'^addtoqueue/(?P<cred_id>\d+)/$', v.addtoqueue, name='addtoqueue'),

    # Bulk views (for buttons on list page)
    re_path(r'^addtoqueue/bulk/$', v.bulkaddtoqueue, name="bulkaddtoqueue"),
    re_path(r'^delete/bulk/$', v.bulkdelete, name="bulkdelete"),
    re_path(r'^undelete/bulk/$', v.bulkundelete, name="bulkundelete"),
    re_path(r'^addtag/bulk/$', v.bulktagcred, name="bulktagcred"),

    # Tags
    re_path(r'^tag/$', v.tags, name="tags"),
    re_path(r'^tag/add/$', v.tagadd, name="tagadd"),
    re_path(r'^tag/edit/(?P<tag_id>\d+)/$', v.tagedit, name="tagedit"),
    re_path(r'^tag/delete/(?P<tag_id>\d+)/$', v.tagdelete, name="tagdelete"),

    # Loginto
    re_path(r'^loginto/(?P<cred_itype>\d+)/(?P<cred_id>\d+)/$', v.loginto, name="loginto"),
    re_path(r'^loginto/phpmyadmin/test/$', v.loginto_phpmyadmin_test, name="loginto_phpmyadmin_test"),
    re_path(r'^loginto/phpmyadmin/(?P<cred_id>\d+)/$', v.loginto_phpmyadmin, name="loginto_phpmyadmin"),
]

if not settings.RATTIC_DISABLE_EXPORT:
    urlpatterns += [
        # Export views
        re_path(r'^export.kdb$', v.download),
        re_path(r'^export-by-(?P<cfilter>\w+)/(?P<value>[^/]*).kdb$', v.download, name='download'),
    ]

ratticweb/urls.py
from django.conf.urls import include, re_path
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from tastypie.api import Api
from cred.api import CredResource, TagResource
from staff.api import GroupResource
from django.conf import settings
from ratticweb import views as main_views
import debug_toolbar

# Configure the error handlers
handler500 = 'ratticweb.views.handle500'
handler404 = 'ratticweb.views.handle404'

# Setup the API
v1_api = Api(api_name='v1')
v1_api.register(CredResource())
v1_api.register(TagResource())
v1_api.register(GroupResource())

# Setup the base paths for applications, and the API
base_urlpatterns = [
    # Apps:
    re_path(r'^$', main_views.home, name='home'),
    re_path(r'^account/', include('account.urls')),
    re_path(r'^cred/', include('cred.urls')),
    re_path(r'^staff/', include('staff.urls')),
    re_path(r'^help/', include('help.urls')),
    # API
    re_path(r'^api/', include(v1_api.urls)),
    # Language
    re_path(r'^i18n/', include('django.conf.urls.i18n')),
    re_path(r'^__debug__/', include(debug_toolbar.urls))
    # two Factor
    # re_path(r'^', include('two_factor.urls')),
]

# If in debug mode enable the Django admin interface
if settings.DEBUG:
    # Uncomment the next two lines to enable the admin:
    from django.contrib import admin
    admin.autodiscover()

    base_urlpatterns += [
        # Uncomment the admin/doc line below to enable admin documentation:
        # path('admin/doc/', django.contrib.admindocs.urls),

        # Uncomment the next line to enable the admin:
        path('admin/', admin.site.urls),
    ]
else:
    from django.views.static import serve
    from .settings import STATIC_ROOT
    base_urlpatterns.append(re_path(r'^static/(?P<path>.*)$', serve, {'document_root': STATIC_ROOT}))

# Strip any leading slash from the RATTIC_ROOT_URL
if settings.RATTIC_ROOT_URL[0] == '/':
    root = settings.RATTIC_ROOT_URL[1:]
else:
    root = settings.RATTIC_ROOT_URL

# Serve RatticDB from an alternate root if requested
urlpatterns = [
    re_path(r'^' + root, include(base_urlpatterns)),
]

# Serve the static files from the right location in dev mode
urlpatterns += staticfiles_urlpatterns()

account/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, Http404, HttpResponse
from django.urls import reverse
# , reverse_lazy
from account.models import ApiKey, ApiKeyForm
from .models import UserProfileForm, LDAPPassChangeForm

from django.views.decorators.debug import sensitive_post_parameters
from django.contrib.auth.decorators import login_required
from django.template.response import TemplateResponse
from django.utils.timezone import now
from django.contrib.auth import login
from django.contrib.auth.views import PasswordChangeView
# from django.contrib.auth.forms import SetPasswordForm
from django.utils import timezone

from user_sessions.views import SessionDeleteView
from two_factor.utils import default_device
from two_factor.views import DisableView, BackupTokensView, SetupView, LoginView
from datetime import timedelta
import uuid


# @login_required
# def rattic_change_password(request, *args, **kwargs):
#     print(request.user)
#     if request.user.has_usable_password():
#         # If a user is changing their password
#         # return PasswordChangeView(request, *args, **kwargs)
#         return " "
#     else:
#         # If a user is setting an initial password
#         kwargs['password_change_form'] = SetPasswordForm
#         # return PasswordChangeView(request, *args, **kwargs)
#         return " llasdf"


class RatticChangePasswordView(PasswordChangeView):
    success_url = "/account"
    template_name = "account_changepass.html"

    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


@login_required
def profile(request):
    # Delete our expired keys
    ApiKey.delete_expired(user=request.user)

    # Get a list of the users API Keys
    keys = ApiKey.objects.filter(user=request.user)
    try:
        backup_tokens = request.user.staticdevice_set.all()[0].token_set.count()
    except IndexError:
        backup_tokens = 0

    # Get a list of the users current sessions
    sessions = request.user.session_set.filter(expire_date__gt=now())

    # Get the current session key
    session_key = request.session.session_key

    # Process the form if we have data coming in
    if request.method == 'POST':
        form = UserProfileForm(request.POST, instance=request.user.profile)
        if form.is_valid():
            form.save()
    else:
        form = UserProfileForm(instance=request.user.profile)

    # Show the template
    return render(request, 'account_profile.html', {
        'keys': keys,
        'sessions': sessions,
        'session_key': session_key,
        'form': form,
        'user': request.user,
        'default_device': default_device(request.user),
        'backup_tokens': backup_tokens,
    })


@login_required
def newapikey(request):
    if request.method == 'POST':
        newkey = ApiKey(user=request.user, active=True)
        form = ApiKeyForm(request.POST, instance=newkey)
        if form.is_valid():
            form.save()
        return render(request, 'account_viewapikey.html', {'key': newkey})
    else:
        form = ApiKeyForm()

    return render(request, 'account_newapikey.html', {'form': form})


@login_required
def deleteapikey(request, key_id):
    key = get_object_or_404(ApiKey, pk=key_id)

    if key.user != request.user:
        raise Http404

    if request.method == 'POST':
        key.delete()
        return HttpResponseRedirect(reverse('account:profile'))

    return render(request, 'account_deleteapikey.html', {'key': key})


# Stolen from django.contrib.auth.views
# modifed to support LDAP errors
@sensitive_post_parameters()
@login_required
def ldap_password_change(request,
                    template_name='account_changepass.html',
                    post_change_redirect='/account/',
                    password_change_form=LDAPPassChangeForm,
                    current_app=None, extra_context=None):
    import ldap

    if post_change_redirect is None:
        post_change_redirect = reverse('account:rattic_change_password_done')
    if request.method == "POST":
        form = password_change_form(user=request.user, data=request.POST)
        if form.is_valid():
            try:
                form.save()
                return HttpResponseRedirect(post_change_redirect)
            except ldap.LDAPError as e:
                return render(request, 'account_ldaperror.html', {
                    'desc': e.message['desc'],
                    'info': e.message['info'],
                })
    else:
        form = password_change_form(user=request.user)
    context = {
        'form': form,
    }
    if extra_context is not None:
        context.update(extra_context)
    return TemplateResponse(request, template_name, context,
                            current_app=current_app)


class RatticSessionDeleteView(SessionDeleteView):
    def get_success_url(self):
        return reverse('account:profile')


class RatticTFADisableView(DisableView):
    template_name = 'account_tfa_disable.html'
    redirect_url = 'account:profile'


class RatticTFABackupTokensView(BackupTokensView):
    template_name = 'account_tfa_backup_tokens.html'
    redirect_url = 'tfa_backup'


class RatticTFASetupView(SetupView):
    template_name = 'account_tfa_setup.html'
    qrcode_url = 'account:tfa_qr'
    redirect_url = 'account:profile'


class RatticTFALoginView(LoginView):
    template_name = 'account_tfa_login.html'


class RatticTFAGenerateApiKey(LoginView):
    def get(self, request, *args, **kwargs):
        res = HttpResponse()
        res.set_cookie("csrftoken", request.META['CSRF_COOKIE'])
        res.status_code=405
        return res

    def render(self, form=None, **kwargs):
        if self.steps.current == 'token':
            device = self.get_device()
            device.generate_challenge()
            res = HttpResponse(device.persistent_id)
            res.status_code = 400
            return res

    def done(self, form_list, **kwargs):
        login(self.request, self.get_user())
        ApiKey.delete_expired(user=self.request.user)

        newkey = ApiKey(user=self.request.user, active=True, expires=timezone.now() + timedelta(minutes=5))
        form = ApiKeyForm({"name": uuid.uuid1()}, instance=newkey)
        if form.is_valid():
            form.save()

        res = HttpResponse(newkey.key)
        res.status_code = 200
        return res

account/templates/account_changepass.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans "Setting New password" %}{% endblock %}

{% block content %}
<p>{% blocktrans %}Please enter your new password twice.{% endblocktrans %}<br />
   {% blocktrans %}So we can verify you typed it in correctly.{% endblocktrans %}</p>
<form class="form-horizontal" action="" method="post">
{% csrf_token %}
   {% for field in form %}
        <div class="control-group">
            {{ field.errors }}
            <label class="control-label" for="{{ field.html_name }}">{{ field.label }}</label>
            <div class="controls">
                {{ field }}
            </div>
        </div>
    {% endfor %}
    <div class="controls">
        <input class="btn btn-primary" type="submit" value="{% trans "Change Password" %}" />
    </div>
</form>
{% endblock %}

account/templates/account_deleteapikey.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans "Delete API Key" %} - {% trans "Rattic" %}{% endblock %}

{% block content %}
<h1>{% trans "Delete API Key" %}</h1>

<p>
{% blocktrans %}Please press confirm if you wish to delete this key{% endblocktrans %}
</p>
<p>
  <strong>{% trans "Name" %}:</strong> {{ key.name }}<br />
  <strong>{% trans "Created" %}: </strong> {{ key.created }}
</p>

<form method="post">
{% csrf_token %}
  <input type="submit" class="btn btn-primary" value="{% trans "Confirm" %}"/>
</form>

{% endblock %}

account/templates/account_ldaperror.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<h1>{% trans "LDAP Error" %}</h1>
<p>{% blocktrans %}Your LDAP server returned the following error:{% endblocktrans %}<br />
<strong>{% trans "Description" %}:</strong> {{desc}}<br />
<strong>{% trans "Further Info" %}:</strong> {{info}}
</p>
{% endblock %}

account/templates/account_profile.html
{% extends "base.html" %}
{% load user_sessions %}
{% load i18n %}

{% block content %}
<h1>{% trans "Your Account" %}</h1>
<form action="" method="POST">{% csrf_token %}
<table class="table table-striped table-bordered table-condensed">
<tr><th>{% trans "Username" %}</th><td>{{ user.username }}</td></tr>
<tr><th>{% trans "Email" %}</th><td>{{ user.email }}</td></tr>

{# If the user has a token #}
{% if default_device %}
<tr><th>{% trans "Two Factor Authentication" %}</th><td>{% trans "Enabled"%} <a href="{% url 'tfa_disable' %}" class="btn btn-mini btn-danger">{% trans "Disable" %}</a></td></tr>
<tr><th>{% trans "Backup Codes Left" %}</th><td>{{ backup_tokens }}
    <a href="{% url "tfa_backup" %}" class="btn btn-mini">{% trans "View Codes" %}</a></td></tr>

{# If the user hasn't made a token yet #}
{% else %}
<tr><th>{% trans "Two Factor Authentication" %}</th><td>{% trans "Disabled" %} <a href="{% url 'account:tfa_setup' %}" class="btn btn-mini">{% trans "Enable now" %}</a></td></tr>

{% endif %}
<tr><th>{% trans "Last Password Change" %}</th><td>{{ user.profile.password_changed }}</td></tr>
<tr><th>{% trans "Groups" %}</th><td>{% for g in user.groups.all %}<a href="{% url "cred:list" "group" g.id %}">{{ g.name }}</a>{% if not forloop.last %}, {% endif %}{% endfor %}</td></tr>
{% for field in form %}
<tr><th>{{ field.label }}</th><td>{{ field }}</td></tr>
{% endfor %}
</table>
<input class="btn btn-primary" type="submit" name="submit" value="{% trans "Save Changes" %}" />

{% if ALLOWPWCHANGE %}
    <a class="btn" href="{% url "account:password_change" %}">
	    {% if user.has_usable_password %}
	        {% trans "Change password" %}
		{% else %}
	        {% trans "Set Password" %}
		{% endif %}
    </a>
{% endif %}

</form>
<h2>{% trans "API Keys" %}</h2>
<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr><td colspan="3">
        <a href="{% url 'account:newapikey' %}" class="btn">{% trans "New API Key" %}</a>
    </td></tr>
    <tr>
      <th>&nbsp;</th>
      <th>{% trans "Key Name" %}</th>
      <th>{% trans "Date generated" %}</th>
      <th>{% trans "Expiry date" %}</th>
    </tr>
  </thead>
  <tbody>
    {% for key in keys %}
      <tr>
        <td>
          <a href="{% url 'account:deleteapikey' key.id %}" class="btn btn-danger">
            <i class="icon-remove"></i>
          </a>
        </td>
        <td>{{ key.name }}</td>
        <td>{{ key.created }}</td>
	{% if key.has_expiry %}
	  <td>{{ key.expires }}</td>
	{% else %}
	  <td>Never</td>
	{% endif %}
      </tr>
    {% empty %}
      <tr><td colspan="3">{% blocktrans %}No API Keys available yet{% endblocktrans %}</td></tr>
    {% endfor %}
  </tbody>
</table>
<h2>{% trans "Current Sessions" %}</h2>
<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th>&nbsp;</th>
      <th>{% trans "Device" %}</th>
      <th>{% trans "IP Address" %}</th>
      <th>{% trans "Last Activity" %}</th>
    </tr>
  </thead>
  <tbody>
    {% for s in sessions %}
      <tr>
        <td>
            <form style="display: inline" action="{% url 'account:kill_session' s.session_key %}" method="post">{% csrf_token %}<button href="" class="btn btn-danger btn-mini">Logout</button></form>
        </td>
        <td>{{ s.user_agent|device }}</td>
        <td>{{ s.ip }}</td>
        <td>{{ s.last_activity|timesince }} {% if session_key == s.session_key %}{% trans "(This Session)" %}{% endif %}</td>
      </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

account/templates/account_tfa_backup_tokens.html
{% extends "base.html" %}
{% load future i18n %}

{% block content %}
  <h1>{% block title %}{% trans "Backup Tokens" %}{% endblock %}</h1>
  <p>{% blocktrans %}Backup tokens can be used when your primary and backup
      phone numbers aren't available. The backup tokens below can be used
      for login verification. If you've used up all your backup tokens, you
      can generate a new set of backup tokens. Only the backup tokens shown
      below will be valid.{% endblocktrans %}</p>

  {% if device.token_set.count %}
    <ul>
      {% for token in device.token_set.all %}
        <li>{{ token.token }}</li>
      {% endfor %}
    </ul>
    <p>{% blocktrans %}Print these tokens and keep them somewhere safe.{% endblocktrans %}</p>
  {% else %}
    <p>{% trans "You don't have any backup codes yet." %}</p>
  {% endif %}

  <form method="post">{% csrf_token %}{{ form }}
    <a href="{% url 'account:profile' %}"
       class="pull-right btn btn-link">{% trans "Back to Account Profile" %}</a>
    <button class="btn btn-primary" type="submit">{% trans "Generate Tokens" %}</button>
  </form>
{% endblock %}

account/templates/account_tfa_disable.html
{% extends "base.html" %}
{% load future i18n %}

{% block content %}
  <h1>{% block title %}{% trans "Disable Two-factor Authentication" %}{% endblock %}</h1>
  <p>{% blocktrans %}You are about to disable two-factor authentication. This
    compromises your account security, are you sure?{% endblocktrans %}</p>
  <form method="post">
    {% csrf_token %}
    <table>{{ form }}</table>
    <button class="btn btn-danger"
            type="submit">{% trans "Disable" %}</button>
  </form>
{% endblock %}

account/templates/account_tfa_login.html
{% extends "base.html" %}
{% load i18n two_factor %}

{% block content %}
  <h1>{% block title %}{% trans "Login" %}{% endblock %}</h1>

  {% if wizard.steps.current == 'auth' %}
    <p>{% blocktrans %}Enter your credentials.{% endblocktrans %}</p>
  {% elif wizard.steps.current == 'token' %}
    {% if device.method == 'call' %}
      <p>{% blocktrans %}We are calling your phone right now, please enter the
        digits you hear.{% endblocktrans %}</p>
    {% elif device.method == 'sms' %}
      <p>{% blocktrans %}We sent you a text message, please enter the tokens we
        sent.{% endblocktrans %}</p>
    {% else %}
      <p>{% blocktrans %}Please enter the tokens generated by your token
        generator.{% endblocktrans %}</p>
    {% endif %}
  {% elif wizard.steps.current == 'backup' %}
    <p>{% blocktrans %}Use this form for entering backup tokens for logging in.
      These tokens have been generated for you to print and keep safe. Please
      enter one of these backup tokens to login to your account.{% endblocktrans %}</p>
  {% endif %}

  <form action="" method="post">{% csrf_token %}
    {% include "two_factor/_wizard_forms.html" %}

    {# hidden submit button to enable [enter] key #}
    <div style="margin-left: -500px"><input type="submit" value=""/></div>

    {% if other_devices %}
      <p>{% trans "Or, alternatively, use one of your backup phones:" %}</p>
      <p>
        {% for other in other_devices %}
        <button name="challenge_device" value="{{ other.persistent_id }}"
                class="btn btn-default btn-block" type="submit">
          {{ other|device_action }}
        </button>
      {% endfor %}</p>
    {% endif %}
    {% if backup_tokens %}
      <p>{% trans "As a last resort, you can use a backup token:" %}</p>
      <p>
        <button name="wizard_goto_step" type="submit" value="backup"
                class="btn btn-default btn-block">{% trans "Use Backup Token" %}</button>
      </p>
    {% endif %}

    {% include "two_factor/_wizard_actions.html" %}
  </form>
{% endblock %}

account/templates/account_tfa_setup.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
  <h1>{% block title %}{% trans "Enable Two-Factor Authentication" %}{% endblock %}</h1>
  {% if wizard.steps.current == 'welcome' %}
    <p>{% blocktrans %}You are about to take your account security to the
        next level. Follow the steps in this wizard to enable two-factor
        authentication.{% endblocktrans %}</p>
  {% elif wizard.steps.current == 'method' %}
    <p>{% blocktrans %}Please select which authentication method you would
        like to use.{% endblocktrans %}</p>
  {% elif wizard.steps.current == 'generator' %}
    <p>{% blocktrans %}To start using a token generator, please use your
        smartphone to scan the QR code below. For example, use Google
        Authenticator. Then, enter the token generated by the app.
        {% endblocktrans %}</p>
    <p><img src="{{ QR_URL }}" alt="QR Code" /></p>
  {% elif wizard.steps.current == 'sms' %}
    <p>{% blocktrans %}Please enter the phone number you wish to receive the
      text messages on. This number will be validated in the next step.
      {% endblocktrans %}</p>
  {% elif wizard.steps.current == 'call' %}
    <p>{% blocktrans %}Please enter the phone number you wish to be called on.
      This number will be validated in the next step. {% endblocktrans %}</p>
  {% elif wizard.steps.current == 'validation' %}
    {% if device.method == 'call' %}
      <p>{% blocktrans %}We are calling your phone right now, please enter the
        digits you hear.{% endblocktrans %}</p>
    {% elif device.method == 'sms' %}
      <p>{% blocktrans %}We sent you a text message, please enter the tokens we
        sent.{% endblocktrans %}</p>
    {% endif %}
  {% endif %}

  <form action="" method="post">{% csrf_token %}
    {% include "two_factor/_wizard_forms.html" %}

    {# hidden submit button to enable [enter] key #}
    <div style="margin-left: -500px"><input type="submit" value=""/></div>

    {% include "two_factor/_wizard_actions.html" %}
  </form>
{% endblock %}

account/templates/account_viewapikey.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans "New API Key" %} - {% trans "Rattic" %}{% endblock %}

{% block content %}
<h1>{% trans "New API Key" %}</h1>

<div class="alert">
  <strong>{% trans "Warning!" %}</strong>
  {% blocktrans %}This is the last chance that you will have to access the secret key. You should save it in a safe place now.{% endblocktrans %}
</div>
<p>
  {% blocktrans %}Your new API key has been created.{% endblocktrans %}
</p>
<p>
  <strong>{% trans "Name" %}:</strong> {{ key.name }}<br />
  <strong>{% trans "Secret Key" %}:</strong> {{ key.key }}
</p>
<p>
  <a href="{% url 'account:profile' %}" class="btn btn-primary">{% trans "Back to Profile" %}</a>
</p>

{% endblock %}

account/templates/password_reset.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "Reset Password" %} - {% trans "Rattic" %}{% endblock %}

{% block content %}
<p>{% blocktrans %}Please specify your email address to receive instructions for resetting it.{% endblocktrans %}</p>

<form action="" method="post">
    <div style="display:none">
        <input type="hidden" value="{{ csrf_token }}" name="csrfmiddlewaretoken">
    </div>
     {{ form.email.errors }}
    <p><label for="id_email">{% trans "E-mail address" %}:</label> {{ form.email }} <input type="submit" value="{% trans "Reset password" %}" /></p>
</form>
{% endblock %}

account/templates/password_reset_complete.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "Password reset complete" %} - {% trans "Rattic" %}{% endblock %}

{% block content %}
<p>{% blocktrans %}Your password has been set. You may go ahead and log in now.{% endblocktrans %}</p>
<p><a href="{{ login_url }}">{% trans "Log in" %}</a></p>
{% endblock %}