account/urls.py
from django.conf.urls import include, re_path, url
from django.conf import settings

from .views import profile, newapikey, deleteapikey, RatticSessionDeleteView
from .views import RatticTFADisableView, RatticTFABackupTokensView
from .views import RatticTFASetupView, RatticTFALoginView
from .views import RatticTFAGenerateApiKey
from .views import RatticChangePasswordView
from .views import ldap_password_change
from django.contrib import auth as dj_auth

from two_factor.views import QRGeneratorView

app_name='account'

urlpatterns = [
    re_path(r'^$', profile, {}, name='profile'),
    re_path(r'^newapikey/$', newapikey, {}, name="newapikey"),
    re_path(r'^deleteapikey/(?P<key_id>\d+)/$', deleteapikey, {}, name="deleteapikey"),

    re_path(r'^logout/$', dj_auth.views.LogoutView.as_view(), name='logout'),

    # View to kill other sessions with
    re_path(r'^killsession/(?P<pk>\w+)/', RatticSessionDeleteView.as_view(), name='kill_session'),

    # Two Factor Views
    re_path(r'^login/$', RatticTFALoginView.as_view(), name='login'),
    re_path(r'^generate_api_key$', RatticTFAGenerateApiKey.as_view(), name="generate_api_key"),

    re_path(r'^two_factor/disable/$', RatticTFADisableView.as_view(), name='tfa_disable'),
    re_path(r'^two_factor/backup/$', RatticTFABackupTokensView.as_view(), name='tfa_backup'),
    re_path(r'^two_factor/setup/$', RatticTFASetupView.as_view(), name='tfa_setup'),
    re_path(r'^two_factor/qr/$', QRGeneratorView.as_view(), name='tfa_qr'),
]

if settings.GOAUTH2_ENABLED:
    urlpatterns += [
        re_path(r'', include('social_auth.urls')),
    ]

# URLs we don't want enabled with LDAP
if not settings.LDAP_ENABLED:
    urlpatterns += [
        re_path(r'^reset/$', dj_auth.views.PasswordResetView.as_view(), {
                'post_reset_redirect': '/account/reset/done/',
                'template_name': 'password_reset.html'},
            name="password_reset"
        ),

        re_path(r'^reset/done/$', dj_auth.views.PasswordResetDoneView.as_view(), {
            'template_name': 'password_reset_done.html'},
            name="password_reset_done"
        ),

        re_path(r'^reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', dj_auth.views.PasswordResetConfirmView.as_view(), {
            'post_reset_redirect': '/',
            'template_name': 'password_reset_confirm.html'},
            name="password_reset_confirm"
        ),

        url(r'^changepass/$', RatticChangePasswordView.as_view(), {
            'post_change_redirect': '/account/',
            'template_name': 'account_changepass.html'}, name='password_change')
    ]

# URLs we do want enabled with LDAP
if settings.LDAP_ENABLED and settings.AUTH_LDAP_ALLOW_PASSWORD_CHANGE:
    urlpatterns += [
        re_path(r'^changepass/$', ldap_password_change, {}, name='password_change')
    ]

cred/urls.py
from django.conf.urls import re_path
from django.conf import settings
import cred.views as v

LOCAL_PREFIX = ""
app_name = 'cred'

urlpatterns = [
    # New list views
    re_path(r'^list/$', v.list, name="list"),
    re_path(r'^list-by-(?P<cfilter>\w+)/(?P<value>[^/]*)/$', v.list, name="list"),
    re_path(r'^list-by-(?P<cfilter>\w+)/(?P<value>[^/]*)/sort-(?P<sortdir>ascending|descending)-by-(?P<sort>\w+)/$', v.list, name="list"),
    re_path(r'^list-by-(?P<cfilter>\w+)/(?P<value>[^/]*)/sort-(?P<sortdir>ascending|descending)-by-(?P<sort>\w+)/page-(?P<page>\d+)/$', v.list, name="list"),

    # Search dialog for mobile
    re_path(r'^search/$', v.search, name='search'),

    # Single cred views
    re_path(r'^detail/(?P<cred_id>\d+)/$', v.detail, name="detail"),
    re_path(r'^detail/(?P<cred_id>\d+)/fingerprint/$', v.ssh_key_fingerprint, name="ssh_key_fingerprint"),
    re_path(r'^detail/(?P<cred_id>\d+)/download/$', v.downloadattachment, name="downloadattachment"),
    re_path(r'^detail/(?P<cred_id>\d+)/ssh_key/$', v.downloadsshkey, name="downloadsshkey"),
    re_path(r'^edit/(?P<cred_id>\d+)/$', v.edit, name='edit'),
    re_path(r'^delete/(?P<cred_id>\d+)/$', v.delete, name='delete'),
    re_path(r'^add/$', v.add, name="add"),

    # Adding to the change queue
    re_path(r'^addtoqueue/(?P<cred_id>\d+)/$', v.addtoqueue, name='addtoqueue'),

    # Bulk views (for buttons on list page)
    re_path(r'^addtoqueue/bulk/$', v.bulkaddtoqueue, name="bulkaddtoqueue"),
    re_path(r'^delete/bulk/$', v.bulkdelete, name="bulkdelete"),
    re_path(r'^undelete/bulk/$', v.bulkundelete, name="bulkundelete"),
    re_path(r'^addtag/bulk/$', v.bulktagcred, name="bulktagcred"),

    # Tags
    re_path(r'^tag/$', v.tags, name="tags"),
    re_path(r'^tag/add/$', v.tagadd, name="tagadd"),
    re_path(r'^tag/edit/(?P<tag_id>\d+)/$', v.tagedit, name="tagedit"),
    re_path(r'^tag/delete/(?P<tag_id>\d+)/$', v.tagdelete, name="tagdelete"),

    # Loginto
    re_path(r'^loginto/(?P<cred_itype>\d+)/(?P<cred_id>\d+)/$', v.loginto, name="loginto"),
    re_path(r'^loginto/phpmyadmin/test/$', v.loginto_phpmyadmin_test, name="loginto_phpmyadmin_test"),
    re_path(r'^loginto/phpmyadmin/(?P<cred_id>\d+)/$', v.loginto_phpmyadmin, name="loginto_phpmyadmin"),
]

if not settings.RATTIC_DISABLE_EXPORT:
    urlpatterns += [
        # Export views
        re_path(r'^export.kdb$', v.download),
        re_path(r'^export-by-(?P<cfilter>\w+)/(?P<value>[^/]*).kdb$', v.download, name='download'),
    ]

help/urls.py
from django.conf.urls import re_path
import help.views as v

app_name = "help"

urlpatterns = [
    re_path(r'^$', v.home),
    re_path(r'^(?P<page>[\w\-]+)/$', v.markdown),
]

ratticweb/urls.py
from django.conf.urls import include, re_path
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from tastypie.api import Api
from cred.api import CredResource, TagResource
from staff.api import GroupResource
from django.conf import settings
from ratticweb import views as main_views
import debug_toolbar

# Configure the error handlers
handler500 = 'ratticweb.views.handle500'
handler404 = 'ratticweb.views.handle404'

# Setup the API
v1_api = Api(api_name='v1')
v1_api.register(CredResource())
v1_api.register(TagResource())
v1_api.register(GroupResource())

# Setup the base paths for applications, and the API
base_urlpatterns = [
    # Apps:
    re_path(r'^$', main_views.home, name='home'),
    re_path(r'^account/', include('account.urls')),
    re_path(r'^cred/', include('cred.urls')),
    re_path(r'^staff/', include('staff.urls')),
    re_path(r'^help/', include('help.urls')),
    # API
    re_path(r'^api/', include(v1_api.urls)),
    # Language
    re_path(r'^i18n/', include('django.conf.urls.i18n')),
    re_path(r'^__debug__/', include(debug_toolbar.urls))
    # two Factor
    # re_path(r'^', include('two_factor.urls')),
]

# If in debug mode enable the Django admin interface
if settings.DEBUG:
    # Uncomment the next two lines to enable the admin:
    from django.contrib import admin
    admin.autodiscover()

    base_urlpatterns += [
        # Uncomment the admin/doc line below to enable admin documentation:
        # path('admin/doc/', django.contrib.admindocs.urls),

        # Uncomment the next line to enable the admin:
        path('admin/', admin.site.urls),
    ]
else:
    from django.views.static import serve
    from .settings import STATIC_ROOT
    base_urlpatterns.append(re_path(r'^static/(?P<path>.*)$', serve, {'document_root': STATIC_ROOT}))

# Strip any leading slash from the RATTIC_ROOT_URL
if settings.RATTIC_ROOT_URL[0] == '/':
    root = settings.RATTIC_ROOT_URL[1:]
else:
    root = settings.RATTIC_ROOT_URL

# Serve RatticDB from an alternate root if requested
urlpatterns = [
    re_path(r'^' + root, include(base_urlpatterns)),
]

# Serve the static files from the right location in dev mode
urlpatterns += staticfiles_urlpatterns()

staff/urls.py
from django.conf.urls import re_path
from django.conf import settings
from .views import NewUser, UpdateUser
import staff.views as v

app_name='staff'

urlpatterns = [
    # Views in views.py
    re_path(r'^$', v.home, name="home"),

    # User/Group Management
    re_path(r'^userdetail/(?P<uid>\d+)/$', v.userdetail, name="userdetail"),
    re_path(r'^removetoken/(?P<uid>\d+)/$', v.removetoken, name='removetoken'),
    re_path(r'^groupdetail/(?P<gid>\d+)/$', v.groupdetail, name='groupdetail'),

    # Auditing
    re_path(r'^audit-by-(?P<by>\w+)/(?P<byarg>\d+)/$', v.audit, name="audit"),

    # Importing
    re_path(r'^import/keepass/$', v.upload_keepass, name="upload_keepass"),
    re_path(r'^import/process/$', v.import_overview, name="import_overview"),
    re_path(r'^import/process/(?P<import_id>\d+)/$', v.import_process, name="import_process"),
    re_path(r'^import/process/(?P<import_id>\d+)/ignore/$', v.import_ignore, name="import_ignore"),

    # Undeletion
    re_path(r'^credundelete/(?P<cred_id>\d+)/$', v.credundelete, name="credundelete"),
]

# URLs we remove if using LDAP groups
if not settings.USE_LDAP_GROUPS:
    urlpatterns += [
        # Group Management
        re_path(r'^groupadd/$', v.groupadd, name="groupadd"),
        re_path(r'^groupedit/(?P<gid>\d+)/$', v.groupedit, name="groupedit"),
        re_path(r'^groupdelete/(?P<gid>\d+)/$', v.groupdelete, name="groupdelete"),
        re_path(r'^useredit/(?P<pk>\d+)/$', UpdateUser.as_view(), name="user_edit"),
        re_path(r'^userdelete/(?P<uid>\d+)/$', v.userdelete, name="userdelete"),
    ]

# User add is disabled only when LDAP config exists
if not settings.LDAP_ENABLED:
    urlpatterns += [
        # User Management
        re_path(r'^useradd/$', NewUser.as_view(), name="user_add"),
    ]

ratticweb/views.py
from django.shortcuts import redirect, render
from django.urls import reverse


def home(request):
    if request.user.is_authenticated:
        return redirect(reverse('cred:list'))
    else:
        nextpage = request.GET.get('next', '')
        return render(request, 'home.html', {'next': nextpage})


def handle500(request):
    return render(request, '500.html', status=500)


def handle404(request):
    return render(request, '404.html', status=404)

ratticweb/templates/base.html
{% load static from staticfiles %}
{% load url_root from ratticweb %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
{% if TEMPLATE_DEBUG %}
<!--
{% debug %}
-->
{% endif %}
<head>
  <title>{% block title %}{% trans "Rattic" %}{% endblock %}</title>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="rattic_url_root" content="{% url_root %}" />
  {% if user.is_staff and USE_LDAP_GROUPS %}
    <meta name="rattic_user_staff" content="true" />
  {% else %}
    <meta name="rattic_user_staff" content="false" />
  {% endif %}
  {% block headarea %}
  {% endblock %}
  <link href="{% static "bootstrap/css/bootstrap.min.css" %}" rel="stylesheet" media="screen">
  <link href="{% static "selectize/0.8.5/css/selectize.css" %}" rel="stylesheet" media="screen">
  <link href="{% static "selectize/0.8.5/css/selectize.bootstrap2.css" %}" rel="stylesheet" media="screen">
  <link href="{% static "rattic/css/base.css" %}" rel="stylesheet" media="screen">
  <link href="{% static "rattic/css/icons.css" %}" rel="stylesheet" media="screen">
  <script src="{% static "modernizr/2.6.2/modernizr.js" %}" ></script>
  <link href="{% static "favicon_new.ico" %}" rel="shortcut icon">
</head>
<body>
<div id="wrap">
    <div class="container-fluid">
         {% include "navbar.html" %}
         <div class="row-fluid">
              <div class="span2 hidden-phone">
                  {% include "sidebar.html" %}
              </div>
              {% block self_span_content %}
                  <div class="span10">
                      {% block content %}{% endblock %}
                  </div>
              {% endblock %}
         </div>
         <div id="push"></div>
    </div>
</div>
<div id="footer">
  <div class="container-fluid">
      <p class="muted credit">{% blocktrans %}Password management powered by{% endblocktrans %} <a href="http://rattic.org/">{% trans "RatticDB" %}</a><span class='hidden-phone'>, {% trans "built by" %} <a href="https://twitter.com/smarthall">@smarthall</a> {% trans "and" %} <a href="https://twitter.com/zemmiph0bia">@zemmiph0bia</a>. | <a href="https://github.com/tildaslash/RatticWeb/issues/new">{% trans "Report an issue" %}</a> | <a href="https://twitter.com/RatticDB">{% trans "Contact Us" %}</a></span></p>
  </div>
</div>
<script type="application/javascript" src="{% static "jquery/js/jquery.min.js" %}"></script>
<script type="application/javascript" src="{% static "bootstrap/js/bootstrap.min.js" %}"></script>
<script type="application/javascript" src="{% static "selectize/0.8.5/js/selectize.min.js" %}"></script>
<script type="application/javascript" src="{% static "zeroclipboard/1.3.2/ZeroClipboard.min.js" %}"></script>
<script type="application/javascript" src="{% static "flash_detect/1.0.4/flash_detect_min.js" %}"></script>
<script type="application/javascript" src="{% static "sjcl/1.0.0/sjcl.js" %}"></script>
<script type="application/javascript" src="{% static "rattic/js/newcore.js" %}"></script>
</body>
</html>

ratticweb/templates/home.html
{% extends "base.html" %}
{% load static from staticfiles %}
{% load i18n %}

{% block content %}
{% if form.errors %}
<div id="loginfailed" class="alert alert-error">
    {% blocktrans %}Your username and password didn't match. Please try again.{% endblocktrans %}
</div>
{% endif %}
<div class="pagination-centered">
    <h1>{% trans "Welcome to Rattic" %}</h1>
	<img class="biglogo" alt="{% trans "RatticDB Logo" %}" src="{% static rattic_logo %}">
    <p>{% trans "It does passwords." %}</p>
    <p class="visible-phone"><a class='btn btn-primary' href="{% url "account:login" %}" >{% trans "Login" %}</a></p>
</div>
{% endblock %}

ratticweb/templates/navbar.html
{% load static from staticfiles %}
{% load url_root from ratticweb %}
{% load i18n %}
{% url "cred:list" as cred_views_list %}
{% url "cred:search" as cred_views_search %}
{% url "cred:list" "special" "changeq" as cred_views_viewqueue %}
{% url "staff:home" as staff_views_home %}
{% url "help:home" as help_views_home %}
<div class="navbar">
    <div class="navbar-inner">
        <a class="brand" href="{% url_root %}"><img class="logo" src="{% static rattic_icon %}" /><span class="hidden-phone"> {% trans "RatticDB" %}</span></a>

        <ul class="nav visible-desktop">
            <li {% if pageurl == cred_views_list %}class="active"{% endif %}>
              <a href="{{ cred_views_list }}">{% trans "Passwords" %}</a>
            </li>
            {% if user.is_authenticated %}
              <li {% if pageurl == cred_views_viewqueue %}class="active"{% endif %}>
                <a href="{{ cred_views_viewqueue }}">{% trans "Change Queue" %}{% if changeqcount > 0 %} <span class="badge">{{ changeqcount }}</span>{% endif %}</a>
              </li>
            {% endif %}
            {% if user.is_staff %}
              <li {% if pageurl == staff_views_home %}class="active"{% endif %}>
                <a href="{{ staff_views_home }}">{% trans "Staff Management" %}</a>
              </li>
            {% endif %}
            {% if helplinks %}
              <li {% if pageurl == help_views_home %}class="active"{% endif %}>
                <a href="{{ help_views_home }}">{% trans "Help" %}</a>
              </li>
            {% endif %}
        </ul>

        <ul class="nav hidden-desktop">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">{% trans "Menu" %} <b class="caret"></b></a>
            <ul class="dropdown-menu" role="menu">
              {% if user.is_authenticated %}
                <li>
                  <a href="{% url "cred:tags" %}">{% trans "Tags" %}</a>
                </li>
                <li>
                  <a href="{{ cred_views_list }}">{% trans "All Passwords" %}</a>
                </li>
                <li>
                  <a href="{{ cred_views_viewqueue }}">{% trans "Change Queue" %}{% if changeqcount > 0 %} <span class="badge">{{ changeqcount }}</span>{% endif %}</a>
                </li>
                {% if user.is_staff %}
                  <li>
                    <a href="{{ staff_views_home }}">{% trans "Staff Management" %}</a>
                  </li>
                {% endif %}
                <li>
                  <a href="{% url "account:logout" %}">{% trans "Logout" %}</a>
                </li>
              {% else %}
                <li>
                  <a href="{% url 'account:login' %}">{% trans "Login" %}</a>
                </li>
              {% endif %}
              {% if helplinks %}
                <li>
                  <a href="{{ help_views_home }}">{% trans "Help" %}</a>
                </li>
              {% endif %}
            </ul>
          </li>
          {% if user.is_authenticated %}
          <li {% if pageurl == cred_views_search %}class="active"{% endif %}>
            <a href="{{ cred_views_search }}">{% trans "Search" %}</a>
          </li>
          {% endif %}
        </ul>

		<ul class="nav pull-right">
		  <li class="dropdown">
		    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"><i class="icon-globe"></i></a>
            <ul class="dropdown-menu" role="menu">
			  {% get_language_info_list for LANGUAGES as langs %}
			  {% for lang in langs %}
			    <li>
				  <a href="#" class="rattic-form-submit-by-id" data-form="#lang-{{ lang.code }}">
				    {{ lang.name_local }}
	              </a>
				  <form id="lang-{{ lang.code }}" class="no-display" action="{% url 'set_language' %}" method="POST">
				    {% csrf_token %}
				    <input type="hidden" name="language" value="{{ lang.code }}" />
			      </form>
				</li>
			  {% endfor %}
		    </ul>
		  </li>
		</ul>

        <form class="navbar-search pull-right hidden-phone rattic-cred-search">
             <input id="search-box" type="search" name="box" class="search-query" placeholder="{% trans "Search" %}">
        </form>
    </div>
</div>

ratticweb/templates/sidebar.html
{% load static from staticfiles %}
{% load i18n %}

{% if user.is_authenticated %}
    <h4>{% trans "You" %}</h4>
        <p>{% blocktrans with username=user.username|title %}Welcome {{ username }}.{% endblocktrans %}<p>
        <a class="btn" href="{% url "account:profile" %}">{% trans "Profile" %}</a>
        <a class="btn btn-danger" href="{% url "account:logout" %}">{% trans "Logout" %}</a>
    <h4><a href="{% url "cred:tags"  %}">{% trans "Tags" %}</a></h4>
    {% if user.is_authenticated %}
        {% for tag in user.profile.favourite_tags.all %}
        <p><i class="icon-minus"></i> <a href="{% url "cred:list" "tag" tag.id %}">{{ tag.name }}</a></p>
        {% empty %}
        <p>{% blocktrans %}Add Favourite Tags on the {% endblocktrans %}
        <a href="{% url 'account:profile' %}">{% trans "profile" %}</a> {% blocktrans %}page to see them here.{% endblocktrans %}</p>
        {% endfor %}
		<h4>{% trans "Groups" %}</h4>
        {% for g in user.groups.all %}
        <p><i class="icon-minus"></i> <a href="{% url "cred:list" "group" g.id %}">{{ g.name }}</a></p>
        {% empty %}
        <p>{% blocktrans %}If you are a member of any groups, you will see them listed here. {% endblocktrans %}</p>
        {% endfor %}
    {% endif %}
{% else %}
<h4>{% trans "Login" %}</h4>
    <form class="form-inline" method="post" action="{% url "account:login" %}?next={{ next|default:'' }}">{% csrf_token %}
			<label for="id_username">{% trans "Username" %}</label><input class="parent-sized" id="id_username" type="text" name="auth-username" maxlength="30" />
			<label for="id_password">{% trans "Password" %}</label><input class="parent-sized" type="password" name="auth-password" id="id_password" />
			<input type="submit" class="btn" value="{% trans "Login" %}"/>
	{% if not LDAP_ENABLED %}<p><a href="{% url "account:password_reset" %}">{% trans "Forgotten password?" %}</a></p>{% endif %}
    <input type="hidden" name="rattic_tfa_login_view-current_step" value="auth" />
    </form>
	{% if GOAUTH2_ENABLED %}
    <div>
			<a href="{% url 'socialauth_begin' 'google-oauth2' %}"><img alt="{% trans "Google Sign-in" %}" src="{% static "rattic/img/goauth.png" %}" /></a>
    </div>
	{% endif %}
{% endif %}