cred/urls.py
from django.conf.urls import re_path
from django.conf import settings
import cred.views as v

LOCAL_PREFIX = ""
app_name = 'cred'

urlpatterns = [
    # New list views
    re_path(r'^list/$', v.list, name="list"),
    re_path(r'^list-by-(?P<cfilter>\w+)/(?P<value>[^/]*)/$', v.list, name="list"),
    re_path(r'^list-by-(?P<cfilter>\w+)/(?P<value>[^/]*)/sort-(?P<sortdir>ascending|descending)-by-(?P<sort>\w+)/$', v.list, name="list"),
    re_path(r'^list-by-(?P<cfilter>\w+)/(?P<value>[^/]*)/sort-(?P<sortdir>ascending|descending)-by-(?P<sort>\w+)/page-(?P<page>\d+)/$', v.list, name="list"),

    # Search dialog for mobile
    re_path(r'^search/$', v.search, name='search'),

    # Single cred views
    re_path(r'^detail/(?P<cred_id>\d+)/$', v.detail, name="detail"),
    re_path(r'^detail/(?P<cred_id>\d+)/fingerprint/$', v.ssh_key_fingerprint, name="ssh_key_fingerprint"),
    re_path(r'^detail/(?P<cred_id>\d+)/download/$', v.downloadattachment, name="downloadattachment"),
    re_path(r'^detail/(?P<cred_id>\d+)/ssh_key/$', v.downloadsshkey, name="downloadsshkey"),
    re_path(r'^edit/(?P<cred_id>\d+)/$', v.edit, name='edit'),
    re_path(r'^delete/(?P<cred_id>\d+)/$', v.delete, name='delete'),
    re_path(r'^add/$', v.add, name="add"),

    # Adding to the change queue
    re_path(r'^addtoqueue/(?P<cred_id>\d+)/$', v.addtoqueue, name='addtoqueue'),

    # Bulk views (for buttons on list page)
    re_path(r'^addtoqueue/bulk/$', v.bulkaddtoqueue, name="bulkaddtoqueue"),
    re_path(r'^delete/bulk/$', v.bulkdelete, name="bulkdelete"),
    re_path(r'^undelete/bulk/$', v.bulkundelete, name="bulkundelete"),
    re_path(r'^addtag/bulk/$', v.bulktagcred, name="bulktagcred"),

    # Tags
    re_path(r'^tag/$', v.tags, name="tags"),
    re_path(r'^tag/add/$', v.tagadd, name="tagadd"),
    re_path(r'^tag/edit/(?P<tag_id>\d+)/$', v.tagedit, name="tagedit"),
    re_path(r'^tag/delete/(?P<tag_id>\d+)/$', v.tagdelete, name="tagdelete"),

    # Loginto
    re_path(r'^loginto/(?P<cred_itype>\d+)/(?P<cred_id>\d+)/$', v.loginto, name="loginto"),
    re_path(r'^loginto/phpmyadmin/test/$', v.loginto_phpmyadmin_test, name="loginto_phpmyadmin_test"),
    re_path(r'^loginto/phpmyadmin/(?P<cred_id>\d+)/$', v.loginto_phpmyadmin, name="loginto_phpmyadmin"),
]

if not settings.RATTIC_DISABLE_EXPORT:
    urlpatterns += [
        # Export views
        re_path(r'^export.kdb$', v.download),
        re_path(r'^export-by-(?P<cfilter>\w+)/(?P<value>[^/]*).kdb$', v.download, name='download'),
    ]

ratticweb/urls.py
from django.conf.urls import include, re_path
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from tastypie.api import Api
from cred.api import CredResource, TagResource
from staff.api import GroupResource
from django.conf import settings
from ratticweb import views as main_views
import debug_toolbar

# Configure the error handlers
handler500 = 'ratticweb.views.handle500'
handler404 = 'ratticweb.views.handle404'

# Setup the API
v1_api = Api(api_name='v1')
v1_api.register(CredResource())
v1_api.register(TagResource())
v1_api.register(GroupResource())

# Setup the base paths for applications, and the API
base_urlpatterns = [
    # Apps:
    re_path(r'^$', main_views.home, name='home'),
    re_path(r'^account/', include('account.urls')),
    re_path(r'^cred/', include('cred.urls')),
    re_path(r'^staff/', include('staff.urls')),
    re_path(r'^help/', include('help.urls')),
    # API
    re_path(r'^api/', include(v1_api.urls)),
    # Language
    re_path(r'^i18n/', include('django.conf.urls.i18n')),
    re_path(r'^__debug__/', include(debug_toolbar.urls))
    # two Factor
    # re_path(r'^', include('two_factor.urls')),
]

# If in debug mode enable the Django admin interface
if settings.DEBUG:
    # Uncomment the next two lines to enable the admin:
    from django.contrib import admin
    admin.autodiscover()

    base_urlpatterns += [
        # Uncomment the admin/doc line below to enable admin documentation:
        # path('admin/doc/', django.contrib.admindocs.urls),

        # Uncomment the next line to enable the admin:
        path('admin/', admin.site.urls),
    ]
else:
    from django.views.static import serve
    from .settings import STATIC_ROOT
    base_urlpatterns.append(re_path(r'^static/(?P<path>.*)$', serve, {'document_root': STATIC_ROOT}))

# Strip any leading slash from the RATTIC_ROOT_URL
if settings.RATTIC_ROOT_URL[0] == '/':
    root = settings.RATTIC_ROOT_URL[1:]
else:
    root = settings.RATTIC_ROOT_URL

# Serve RatticDB from an alternate root if requested
urlpatterns = [
    re_path(r'^' + root, include(base_urlpatterns)),
]

# Serve the static files from the right location in dev mode
urlpatterns += staticfiles_urlpatterns()

staff/urls.py
from django.conf.urls import re_path
from django.conf import settings
from .views import NewUser, UpdateUser
import staff.views as v

app_name='staff'

urlpatterns = [
    # Views in views.py
    re_path(r'^$', v.home, name="home"),

    # User/Group Management
    re_path(r'^userdetail/(?P<uid>\d+)/$', v.userdetail, name="userdetail"),
    re_path(r'^removetoken/(?P<uid>\d+)/$', v.removetoken, name='removetoken'),
    re_path(r'^groupdetail/(?P<gid>\d+)/$', v.groupdetail, name='groupdetail'),

    # Auditing
    re_path(r'^audit-by-(?P<by>\w+)/(?P<byarg>\d+)/$', v.audit, name="audit"),

    # Importing
    re_path(r'^import/keepass/$', v.upload_keepass, name="upload_keepass"),
    re_path(r'^import/process/$', v.import_overview, name="import_overview"),
    re_path(r'^import/process/(?P<import_id>\d+)/$', v.import_process, name="import_process"),
    re_path(r'^import/process/(?P<import_id>\d+)/ignore/$', v.import_ignore, name="import_ignore"),

    # Undeletion
    re_path(r'^credundelete/(?P<cred_id>\d+)/$', v.credundelete, name="credundelete"),
]

# URLs we remove if using LDAP groups
if not settings.USE_LDAP_GROUPS:
    urlpatterns += [
        # Group Management
        re_path(r'^groupadd/$', v.groupadd, name="groupadd"),
        re_path(r'^groupedit/(?P<gid>\d+)/$', v.groupedit, name="groupedit"),
        re_path(r'^groupdelete/(?P<gid>\d+)/$', v.groupdelete, name="groupdelete"),
        re_path(r'^useredit/(?P<pk>\d+)/$', UpdateUser.as_view(), name="user_edit"),
        re_path(r'^userdelete/(?P<uid>\d+)/$', v.userdelete, name="userdelete"),
    ]

# User add is disabled only when LDAP config exists
if not settings.LDAP_ENABLED:
    urlpatterns += [
        # User Management
        re_path(r'^useradd/$', NewUser.as_view(), name="user_add"),
    ]

cred/models.py
from django.db import models
from django.db.models import Q
from django.contrib import admin
from django.contrib.auth.models import User, Group
from django.utils.translation import ugettext_lazy as _
from django.forms.models import model_to_dict
from django.utils.timezone import now
from django.conf import settings

from ratticweb.util import DictDiffer, field_file_compare
from .ssh_key import SSHKey
from .fields import SizedFileField
from .storage import CredAttachmentStorage

CRED_TYPE=(
        (0, "Normal"),
        (1, "Mysql"),
        (2, "GameBackend"),
        )


class Tag(models.Model):
    name = models.CharField(max_length=64, unique=True)

    def __unicode__(self):
        return self.name

    def visible_count(self, user):
        return Cred.objects.visible(user).filter(tags=self).count()


class CredIconAdmin(admin.ModelAdmin):
    list_display = ('name', 'filename')


class SearchManager(models.Manager):
    def visible(self, user, historical=False, deleted=False):
        usergroups = user.groups.all()
        qs = super(SearchManager, self).get_queryset()

        if not user.is_staff or not deleted:
            qs = qs.exclude(is_deleted=True, latest=None)

        if not historical:
            qs = qs.filter(latest=None)

        qs = qs.filter(Q(group__in=usergroups)
                     | Q(latest__group__in=usergroups)
                     | Q(groups__in=usergroups)
                     | Q(latest__groups__in=usergroups)).distinct()

        return qs

    def change_advice(self, user, grouplist=[]):
        logs = CredAudit.objects.filter(
            # Get a list of changes done
            Q(cred__group__in=grouplist, audittype=CredAudit.CREDCHANGE) |
            # Combined with a list of views from this user
            Q(cred__group__in=grouplist, audittype__in=[CredAudit.CREDVIEW, CredAudit.CREDPASSVIEW, CredAudit.CREDADD, CredAudit.CREDEXPORT], user=user)
        ).order_by('time', 'id')

        # Go through each entry in time order
        tochange = []
        for l in logs:
            # If this user viewed the password then change it
            if l.audittype in (CredAudit.CREDVIEW, CredAudit.CREDPASSVIEW, CredAudit.CREDADD, CredAudit.CREDEXPORT):
                tochange.append(l.cred.id)
            # If there was a change done not by this user, dont change it
            if l.audittype == CredAudit.CREDCHANGE and l.user != user:
                if l.cred.id in tochange:
                    tochange.remove(l.cred.id)

        # Fetch the list of credentials to change from the DB for the view
        return Cred.objects.filter(id__in=tochange)


class Cred(models.Model):
    METADATA = ('description', 'descriptionmarkdown', 'group', 'groups', 'tags', 'iconname', 'latest', 'id', 'modified', 'attachment_name', 'ssh_key_name')
    SORTABLES = ('title', 'username', 'group', 'id', 'modified')
    APP_SET = ('is_deleted', 'latest', 'modified', 'attachment_name', 'ssh_key_name')
    objects = SearchManager()

    # User changable fields
    title = models.CharField(verbose_name=_('Title'), max_length=64, db_index=True)
    itype = models.PositiveIntegerField(verbose_name=_('Type'), choices=CRED_TYPE, default=0 )
    url = models.URLField(verbose_name=_('URL'), blank=True, null=True, db_index=True)
    ip_addr = models.GenericIPAddressField(verbose_name=_('IP Address'), blank=True, null=True, db_index=True)
    ip_port = models.PositiveIntegerField(verbose_name=_('IP Port'), blank=True, null=True, db_index=True)
    username = models.CharField(verbose_name=_('Username'), max_length=250, blank=True, null=True, db_index=True)
    password = models.CharField(verbose_name=_('Password'), max_length=250, blank=True, null=True)
    descriptionmarkdown = models.BooleanField(verbose_name=_('Markdown Description'), default=False, )
    description = models.TextField(verbose_name=_('Description'), blank=True, null=True)
    group = models.ForeignKey(Group, verbose_name=_('Group'), on_delete=models.CASCADE)
    groups = models.ManyToManyField(Group, verbose_name=_('Groups'), related_name="child_creds", blank=True, default=None)
    tags = models.ManyToManyField(Tag, verbose_name=_('Tags'), related_name='child_creds', blank=True, default=None)
    iconname = models.CharField(verbose_name=_('Icon'), default='Key.png', max_length=64)
    ssh_key = SizedFileField(verbose_name=_('SSH key'), storage=CredAttachmentStorage(), max_upload_size=settings.RATTIC_MAX_ATTACHMENT_SIZE, null=True, blank=True, upload_to='not required')
    attachment = SizedFileField(verbose_name=_('Attachment'), storage=CredAttachmentStorage(), max_upload_size=settings.RATTIC_MAX_ATTACHMENT_SIZE, null=True, blank=True, upload_to='not required')

    # Application controlled fields
    is_deleted = models.BooleanField(default=False, db_index=True)
    latest = models.ForeignKey('Cred', related_name='history', blank=True, null=True, db_index=True, on_delete=models.CASCADE)
    modified = models.DateTimeField(db_index=True)
    created = models.DateTimeField(auto_now_add=True)

    ssh_key_name = models.CharField(max_length=64, null=True, blank=True)
    attachment_name = models.CharField(max_length=64, null=True, blank=True)

    def save(self, *args, **kwargs):
        try:
            # Get a copy of the old object from the db
            old = Cred.objects.get(id=self.id)

            # Reset the primary key so Django thinks its a new object
            old.id = None

            # Set the latest on the old copy to the new copy
            old.latest = self

            # Create it in the DB
            old.save()

            # Add the tags to the old copy now that it exists
            for t in self.tags.all():
                old.tags.add(t)

            # Add the groups
            for g in self.groups.all():
                old.groups.add(g)

            # Lets see what was changed
            oldcred = model_to_dict(old)
            newcred = model_to_dict(self)
            diff = DictDiffer(newcred, oldcred).changed()

            # Ohhhkaaay, so the attachment field looks like its changed every
            # time, so we do a deep comparison, if the files match we remove
            # it from the list of changed fields.
            for field in ('attachment', 'ssh_key'):
                if field_file_compare(oldcred[field], newcred[field]):
                    diff = diff - set((field, ))

            # Check if some non-metadata was changed
            chg = diff - set(Cred.METADATA)
            cred_changed = len(chg) > 0

            # If the creds were changed update the modify date
            if cred_changed:
                self.modified = now()
        except Cred.DoesNotExist:
            # This just means its new cred, set the initial modified time
            self.modified = now()

        super(Cred, self).save(*args, **kwargs)

    def delete(self):
        if not self.is_deleted:
            self.is_deleted = True
            self.save()
        else:
            super(Cred, self).delete()

    def on_changeq(self):
        return CredChangeQ.objects.filter(cred=self).exists()

    def is_latest(self):
        return self.latest is None

    def is_owned_by(self, user):
        # Staff can do anything
        if user.is_staff:
            return True

        # If its the latest and in your group you can see it
        if not self.is_deleted and self.latest is None and self.group in user.groups.all():
            return True

        # If the latest is in your group you can see it
        if not self.is_deleted and self.latest is not None and self.latest.group in user.groups.all():
            return True

        return False

    def is_visible_by(self, user):
        # Staff can see anything
        if user.is_staff:
            return True

        # If its the latest and (in your group or it belongs to a viewer group you also belong to) you can see it
        if not self.is_deleted and self.latest is None and (self.group in user.groups.all() or any([g in user.groups.all() for g in self.groups.all()])):
            return True

        # If the latest is in your group you can see it
        if not self.is_deleted and self.latest is not None and (self.latest.group in user.groups.all() or any([g in user.groups.all() for g in self.latest.groups.all()])):
            return True

        return False

    def ssh_key_fingerprint(self):
        return SSHKey(self.ssh_key.read(), self.password).fingerprint()

    def __unicode__(self):
        return self.title.encode('utf-8')


class CredAdmin(admin.ModelAdmin):
    list_display = ('title', 'username', 'group')


class CredAudit(models.Model):
    CREDADD = 'A'
    CREDCHANGE = 'C'
    CREDMETACHANGE = 'M'
    CREDVIEW = 'V'
    CREDEXPORT = 'X'
    CREDPASSVIEW = 'P'
    CREDDELETE = 'D'
    CREDSCHEDCHANGE = 'S'
    CREDLOGINTO = 'L'
    CREDAUDITCHOICES = (
        (CREDADD, _('Added')),
        (CREDCHANGE, _('Changed')),
        (CREDMETACHANGE, _('Only Metadata Changed')),
        (CREDVIEW, _('Only Details Viewed')),
        (CREDEXPORT, _('Exported')),
        (CREDDELETE, _('Deleted')),
        (CREDSCHEDCHANGE, _('Scheduled For Change')),
        (CREDPASSVIEW, _('Password Viewed')),
        (CREDLOGINTO, _('Login To')),
    )

    audittype = models.CharField(max_length=1, choices=CREDAUDITCHOICES)
    cred = models.ForeignKey(Cred, related_name='logs', on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='credlogs', on_delete=models.CASCADE)
    time = models.DateTimeField(auto_now_add=True)

    class Meta:
        get_latest_by = 'time'
        ordering = ('-time',)


class CredAuditAdmin(admin.ModelAdmin):
    list_display = ('audittype', 'user', 'cred', 'time')


class CredChangeQManager(models.Manager):
    def add_to_changeq(self, cred):
        return self.get_or_create(cred=cred)

    def for_user(self, user):
        return self.filter(cred__in=Cred.objects.visible(user))


class CredChangeQ(models.Model):

staff/templates/staff_audit.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}

{% include "staff_part_audit_filter.html" %}

{% if by == 'cred' %}
  <h2>{% blocktrans with cred_title=item.title %}Audit Logs for password &apos;{{ cred_title }}&apos;{% endblocktrans %}</h2>
{% endif %}
{% if by == 'user' %}
  <h2>{% blocktrans with username=item.username %}Audit Logs for user &apos;{{ username }}&apos;{% endblocktrans %}</h2>
{% endif %}
{% if by == 'days' %}
  <h2>{% blocktrans %}Audit Logs going back {{ item }} days ago{% endblocktrans %}</h2>
{% endif %}

<table class="table table-striped table-bordered table-condensed">
<tr>

    <th>
        {% trans "Action" %}
        <a href="#filterModal" data-toggle="modal"><i class="icon-filter"></i></a>
    </th>

  {% if type != 'user' %}
    <th>{% trans "User" %}</th>
  {% endif %}
  {% if type != 'cred' %}
    <th>{% trans "Credential" %}</th>
  {% endif %}
  <th>{% trans "When" %}</th>
</tr>

{% for audit in logs %}
  <tr>
    <td>{{ audit.get_audittype_display }}</td>
    {% if by != 'user' %}
      <td><a href="{% url 'staff:userdetail' audit.user.id %}">{{ audit.user.username }}</a></td>
    {% endif %}
    {% if vy != 'cred' %}
      <td><a href="{% url 'cred:detail' audit.cred.id %}">{{ audit.cred.title }}</a></td>
    {% endif %}
    <td>{{ audit.time }}</td>
  </tr>
{% endfor %}
</table>

<div class="pagination pagination-centered">
  <ul>
    {% if logs.has_previous %}
      <li><a href="?page={{ logs.previous_page_number }}">{% trans "Prev" %}</a></li>
    {% else %}
      <li class="disabled"><a href="#">{% trans "Prev" %}</a></li>
    {% endif %}
    {% for p in logs.paginator.page_range %}
      {% if logs.number == p %}
        <li class="active"><a href="#">{{ p }}</a></li>
      {% else %}
        <li><a href="?page={{ p }}">{{ p }}</a></li>
      {% endif %}
    {% endfor %}
    {% if logs.has_next %}
      <li><a href="?page={{ logs.next_page_number }}">{% trans "Next" %}</a></li>
    {% else %}
      <li class="disabled"><a href="#">{% trans "Next" %}</a></li>
    {%endif %}
  </ul>
</div>

{% endblock %}

staff/templates/staff_changeadvice.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<h2>{% blocktrans with username=viewuser.username %}Changes for user: {{ username }}{% endblocktrans %}</h2>
<p>{% blocktrans %}We noticed that you are disabling a user account, or removing groups
from a user. To help you RatticDB has analysed the auditlogs to see what
passwords the user knows, and no longer has access to. We recommend that
you add all these passwords to the change queue. To do this press the
&quot;Add to Change Queue&quot; button, if you don't want to change some
of the passwords, simply uncheck them first.{% endblocktrans %}</p>

<form method="POST" action="{% url "cred:bulkaddtoqueue" %}">{% csrf_token %}
<table class="table table-striped table-bordered table-condensed">
<thead>
<tr>
    <th><input onclick="copycheckbox('all', 'credcheck')" type="checkbox" checked="true" name="all" value="" /></th>
    <th>{% trans "Title" %}</th>
    <th>{% trans "User" %}</th>
    <th>{% trans "Group" %}</th>
    <th>{% trans "Tags" %}</th>
</tr>
</thead>
<tbody>
{% for c in creds %}
<tr>
    <td><input type="checkbox" checked="true" name="credcheck" value="{{ c.id }}" /></td>
    <td><a href="{% url "cred:detail" c.id %}">{{ c.title }}</a></td>
    <td>{{ c.username }}</td>
    <td>{{ c.group.name }}</td>
    <td>{% for t in c.tags.all %}{% if not forloop.first %}, {% endif %}<a href="{% url "cred:list" "tag" t.id %}">{{ t.name }}</a>{% endfor %}</td>
</tr>
{% endfor %}
</tbody>
</table>
<input type="submit" class="btn" value="{% trans "Add to Change Queue" %}" />
</form>

{% endblock %}

staff/templates/staff_groupdetail.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
{% if delete %}
<h1>{% trans "Delete Group" %}: {{ group.name }}</h1>
<div class="alert alert-error">{% blocktrans %}Deleting this group will delete every password underneath it.{% endblocktrans %}</div>
{% else %}
<h1>{% trans "Group" %} {{ group.name }}</h1>
{% if not USE_LDAP_GROUPS %}
<div class="btn-group">
    <a class="btn" href="{% url "staff:groupedit" group.id %}">{% trans "Edit" %}</a>
    <a class="btn btn-danger" href="{% url "staff:groupdelete" group.id %}">{% trans "Delete" %}</a> 
</div>
<br /><br />
{% endif %}
{% endif %}
<table class="table table-striped table-bordered table-condensed">
<tr><th>{% trans "Name" %}</th><td>{{ group.name }}</td></tr>
<tr><th>{% trans "Users" %}</th><td>{% for u in group.user_set.all %}<a href="{% url "staff:userdetail" u.id %}">{{ u.username }}</a>, {% endfor %}</td></tr>
<tr><th>{% trans "Passwords" %}</th><td>{% for c in group.cred_set.all %}<a href="{% url "cred:detail" c.id %}">{{ c.title }}</a>, {% endfor %}</td></tr>
</table>
{% if delete %}
    <form action="{% url "staff:groupdelete" group.id %}" method="post">{% csrf_token %}
        <input type="submit" class="btn btn-danger" value="{% trans "Delete forever" %}" />
    </form>
{% endif %}
{% endblock %}

staff/templates/staff_home.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "Staff" %} - {% trans "Rattic" %}{% endblock %}

{% block content %}
<h1>{% trans "Staff Manage" %}</h1>

<div class="btn-group">
  {% if not LDAP_ENABLED %}
    <a class="btn" href="{% url "staff:user_add" %}">{% trans "Add User" %}</a>
  {% endif %}

  {% if not USE_LDAP_GROUPS %}
    <a class="btn" href="{% url "staff:groupadd" %}">{% trans "Add Group" %}</a>
  {% endif %}
  <a class="btn" href="{% url "staff:upload_keepass" %}">{% trans "Import Keepass" %}</a>
  <a class="btn" href="{% url "cred:list" 'special' 'trash' %}">{% trans "View Trash" %}</a>
  <a class="btn" href="{% url "staff:audit" "days" 7 %}">{% trans "Audit One Week" %}</a>
</div>

<h2>{% trans "Users" %}</h2>
<table class="table table-striped table-bordered table-condensed">
  <tr>
    <th>{% trans "Username" %}</th>
    <th>{% trans "email" %}</th>
    {% if not LDAP_ENABLED %}
    <th>{% trans "Edit" %}</th>
    <th>{% trans "Delete" %}</th>
    {% endif %}
  </tr>
{% for u in userlist %}
<tr {% if not u.is_active %}class="error"{% endif %}>
  <td><a href="{% url "staff:userdetail" u.id %}">{{ u.username }}</a></td>
  <td>{{ u.email }}</td>
  {% if not LDAP_ENABLED %}
  <td><a href="{% url "staff:user_edit" u.id %}">{% trans "Edit" %}</a></td>
  <td><a href="{% url "staff:userdelete" u.id %}">{% trans "Delete" %}</a></td>
  {% endif %}
</tr>
{% endfor %}
</table>

<h2>{% trans "Access Groups" %}</h2>
<table class="table table-striped table-bordered table-condensed">
  <tr><th>{% trans "Name" %}</th>{% if not USE_LDAP_GROUPS %}<th>{% trans "Edit" %}</th><th>{% trans "Delete" %}</th>{% endif %}</tr>
{% for g in grouplist %}
<tr>
  <td><a href="{% url "staff:groupdetail" g.id %}">{{ g.name }}</a></td>
  {% if not USE_LDAP_GROUPS %}
    <td><a href="{% url "staff:groupedit" g.id %}">{% trans "Edit" %}</a></td>
    <td><a href="{% url "staff:groupdelete" g.id %}">{% trans "Delete" %}</a></td>
  {% endif %}
</tr>
{% endfor %}
</table>
{% endblock %}

staff/templates/staff_import_overview.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<h1>{% trans "Import Overview" %}</h1>
<table class="table table-striped table-bordered table-condensed">
<thead>
<tr>
    <th>{% trans "Actions" %}</th>
    <th>{% trans "Title" %}</th>
    <th>{% trans "User" %}</th>
</tr>
</thead>
<tbody>
{% for e in entries %}
<tr>
    <td>
        <a class="btn btn-mini btn-success" href="{% url "staff:import_process" forloop.counter0 %}">{% trans "Import" %}</a>
        <a class="btn btn-mini btn-danger" href="{% url "staff:import_ignore" forloop.counter0 %}">{% trans "Skip" %}</a>
    </td>
    <td>{{ e.title }}</td>
    <td>{{ e.username }}</td>
</tr>
{% endfor %}
</tbody>
</table>
{% endblock %}

staff/templates/staff_userdetail.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
{% if delete %}
<div class="alert alert-error">
  {% blocktrans %}
    Deleting this user will remove any associated auditlogs, maybe deactivate
    their account instead?
  {% endblocktrans %}
</div>
{% endif %}
<h1>{% trans "User" %}: {{ viewuser.username }}</h1>
{% if not LDAP_ENABLED or not USE_LDAP_GROUPS %}
    <div class="btn-group">
    {% if delete %}
        <form action="{% url "staff:userdelete" viewuser.id %}" method="post">{% csrf_token %}
            <input type="submit" class="btn btn-danger" value="{% trans "Confirm Delete" %}" />
        </form>
    {% else %}
        <a class="btn" href="{% url "staff:user_edit" viewuser.id %}">{% trans "Edit" %}</a>
        {% if hastoken %}<a class="btn btn-warning" href="{% url "staff:removetoken" viewuser.id %}">{% trans "Disable Two Factor" %}</a>{% endif %}
        <a class="btn btn-danger" href="{% url "staff:userdelete" viewuser.id %}">{% trans "Delete" %}</a>
    {% endif %}
    </div>
    <p></p>
{% else %}
    {% if hastoken %}<a class="btn btn-warning" href="{% url "staff:removetoken" viewuser.id %}">Disable Two Factor</a>{% endif %}
{% endif %}
<table class="table table-striped table-bordered table-condensed">
<tr><th>{% trans "Email" %}</th><td>{{ viewuser.email }}</td></tr>
<tr><th>{% trans "Groups" %}</th><td>{% for g in viewuser.groups.all %}<a href="{% url "staff:groupdetail" g.id %}">{{ g.name }}</a>, {% endfor %}</td></tr>
</table>
{% if not delete %}
{% include "credaudit_list.html" with type='cred' %}
{% endif %}
{% endblock %}