cred/urls.py
from django.conf.urls import re_path
from django.conf import settings
import cred.views as v

LOCAL_PREFIX = ""
app_name = 'cred'

urlpatterns = [
    # New list views
    re_path(r'^list/$', v.list, name="list"),
    re_path(r'^list-by-(?P<cfilter>\w+)/(?P<value>[^/]*)/$', v.list, name="list"),
    re_path(r'^list-by-(?P<cfilter>\w+)/(?P<value>[^/]*)/sort-(?P<sortdir>ascending|descending)-by-(?P<sort>\w+)/$', v.list, name="list"),
    re_path(r'^list-by-(?P<cfilter>\w+)/(?P<value>[^/]*)/sort-(?P<sortdir>ascending|descending)-by-(?P<sort>\w+)/page-(?P<page>\d+)/$', v.list, name="list"),

    # Search dialog for mobile
    re_path(r'^search/$', v.search, name='search'),

    # Single cred views
    re_path(r'^detail/(?P<cred_id>\d+)/$', v.detail, name="detail"),
    re_path(r'^detail/(?P<cred_id>\d+)/fingerprint/$', v.ssh_key_fingerprint, name="ssh_key_fingerprint"),
    re_path(r'^detail/(?P<cred_id>\d+)/download/$', v.downloadattachment, name="downloadattachment"),
    re_path(r'^detail/(?P<cred_id>\d+)/ssh_key/$', v.downloadsshkey, name="downloadsshkey"),
    re_path(r'^edit/(?P<cred_id>\d+)/$', v.edit, name='edit'),
    re_path(r'^delete/(?P<cred_id>\d+)/$', v.delete, name='delete'),
    re_path(r'^add/$', v.add, name="add"),

    # Adding to the change queue
    re_path(r'^addtoqueue/(?P<cred_id>\d+)/$', v.addtoqueue, name='addtoqueue'),

    # Bulk views (for buttons on list page)
    re_path(r'^addtoqueue/bulk/$', v.bulkaddtoqueue, name="bulkaddtoqueue"),
    re_path(r'^delete/bulk/$', v.bulkdelete, name="bulkdelete"),
    re_path(r'^undelete/bulk/$', v.bulkundelete, name="bulkundelete"),
    re_path(r'^addtag/bulk/$', v.bulktagcred, name="bulktagcred"),

    # Tags
    re_path(r'^tag/$', v.tags, name="tags"),
    re_path(r'^tag/add/$', v.tagadd, name="tagadd"),
    re_path(r'^tag/edit/(?P<tag_id>\d+)/$', v.tagedit, name="tagedit"),
    re_path(r'^tag/delete/(?P<tag_id>\d+)/$', v.tagdelete, name="tagdelete"),

    # Loginto
    re_path(r'^loginto/(?P<cred_itype>\d+)/(?P<cred_id>\d+)/$', v.loginto, name="loginto"),
    re_path(r'^loginto/phpmyadmin/test/$', v.loginto_phpmyadmin_test, name="loginto_phpmyadmin_test"),
    re_path(r'^loginto/phpmyadmin/(?P<cred_id>\d+)/$', v.loginto_phpmyadmin, name="loginto_phpmyadmin"),
]

if not settings.RATTIC_DISABLE_EXPORT:
    urlpatterns += [
        # Export views
        re_path(r'^export.kdb$', v.download),
        re_path(r'^export-by-(?P<cfilter>\w+)/(?P<value>[^/]*).kdb$', v.download, name='download'),
    ]

ratticweb/urls.py
from django.conf.urls import include, re_path
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from tastypie.api import Api
from cred.api import CredResource, TagResource
from staff.api import GroupResource
from django.conf import settings
from ratticweb import views as main_views
import debug_toolbar

# Configure the error handlers
handler500 = 'ratticweb.views.handle500'
handler404 = 'ratticweb.views.handle404'

# Setup the API
v1_api = Api(api_name='v1')
v1_api.register(CredResource())
v1_api.register(TagResource())
v1_api.register(GroupResource())

# Setup the base paths for applications, and the API
base_urlpatterns = [
    # Apps:
    re_path(r'^$', main_views.home, name='home'),
    re_path(r'^account/', include('account.urls')),
    re_path(r'^cred/', include('cred.urls')),
    re_path(r'^staff/', include('staff.urls')),
    re_path(r'^help/', include('help.urls')),
    # API
    re_path(r'^api/', include(v1_api.urls)),
    # Language
    re_path(r'^i18n/', include('django.conf.urls.i18n')),
    re_path(r'^__debug__/', include(debug_toolbar.urls))
    # two Factor
    # re_path(r'^', include('two_factor.urls')),
]

# If in debug mode enable the Django admin interface
if settings.DEBUG:
    # Uncomment the next two lines to enable the admin:
    from django.contrib import admin
    admin.autodiscover()

    base_urlpatterns += [
        # Uncomment the admin/doc line below to enable admin documentation:
        # path('admin/doc/', django.contrib.admindocs.urls),

        # Uncomment the next line to enable the admin:
        path('admin/', admin.site.urls),
    ]
else:
    from django.views.static import serve
    from .settings import STATIC_ROOT
    base_urlpatterns.append(re_path(r'^static/(?P<path>.*)$', serve, {'document_root': STATIC_ROOT}))

# Strip any leading slash from the RATTIC_ROOT_URL
if settings.RATTIC_ROOT_URL[0] == '/':
    root = settings.RATTIC_ROOT_URL[1:]
else:
    root = settings.RATTIC_ROOT_URL

# Serve RatticDB from an alternate root if requested
urlpatterns = [
    re_path(r'^' + root, include(base_urlpatterns)),
]

# Serve the static files from the right location in dev mode
urlpatterns += staticfiles_urlpatterns()

staff/urls.py
from django.conf.urls import re_path
from django.conf import settings
from .views import NewUser, UpdateUser
import staff.views as v

app_name='staff'

urlpatterns = [
    # Views in views.py
    re_path(r'^$', v.home, name="home"),

    # User/Group Management
    re_path(r'^userdetail/(?P<uid>\d+)/$', v.userdetail, name="userdetail"),
    re_path(r'^removetoken/(?P<uid>\d+)/$', v.removetoken, name='removetoken'),
    re_path(r'^groupdetail/(?P<gid>\d+)/$', v.groupdetail, name='groupdetail'),

    # Auditing
    re_path(r'^audit-by-(?P<by>\w+)/(?P<byarg>\d+)/$', v.audit, name="audit"),

    # Importing
    re_path(r'^import/keepass/$', v.upload_keepass, name="upload_keepass"),
    re_path(r'^import/process/$', v.import_overview, name="import_overview"),
    re_path(r'^import/process/(?P<import_id>\d+)/$', v.import_process, name="import_process"),
    re_path(r'^import/process/(?P<import_id>\d+)/ignore/$', v.import_ignore, name="import_ignore"),

    # Undeletion
    re_path(r'^credundelete/(?P<cred_id>\d+)/$', v.credundelete, name="credundelete"),
]

# URLs we remove if using LDAP groups
if not settings.USE_LDAP_GROUPS:
    urlpatterns += [
        # Group Management
        re_path(r'^groupadd/$', v.groupadd, name="groupadd"),
        re_path(r'^groupedit/(?P<gid>\d+)/$', v.groupedit, name="groupedit"),
        re_path(r'^groupdelete/(?P<gid>\d+)/$', v.groupdelete, name="groupdelete"),
        re_path(r'^useredit/(?P<pk>\d+)/$', UpdateUser.as_view(), name="user_edit"),
        re_path(r'^userdelete/(?P<uid>\d+)/$', v.userdelete, name="userdelete"),
    ]

# User add is disabled only when LDAP config exists
if not settings.LDAP_ENABLED:
    urlpatterns += [
        # User Management
        re_path(r'^useradd/$', NewUser.as_view(), name="user_add"),
    ]

cred/models.py
from django.db import models
from django.db.models import Q
from django.contrib import admin
from django.contrib.auth.models import User, Group
from django.utils.translation import ugettext_lazy as _
from django.forms.models import model_to_dict
from django.utils.timezone import now
from django.conf import settings

from ratticweb.util import DictDiffer, field_file_compare
from .ssh_key import SSHKey
from .fields import SizedFileField
from .storage import CredAttachmentStorage

CRED_TYPE=(
        (0, "Normal"),
        (1, "Mysql"),
        (2, "GameBackend"),
        )


class Tag(models.Model):
    name = models.CharField(max_length=64, unique=True)

    def __unicode__(self):
        return self.name

    def visible_count(self, user):
        return Cred.objects.visible(user).filter(tags=self).count()


class CredIconAdmin(admin.ModelAdmin):
    list_display = ('name', 'filename')


class SearchManager(models.Manager):
    def visible(self, user, historical=False, deleted=False):
        usergroups = user.groups.all()
        qs = super(SearchManager, self).get_queryset()

        if not user.is_staff or not deleted:
            qs = qs.exclude(is_deleted=True, latest=None)

        if not historical:
            qs = qs.filter(latest=None)

        qs = qs.filter(Q(group__in=usergroups)
                     | Q(latest__group__in=usergroups)
                     | Q(groups__in=usergroups)
                     | Q(latest__groups__in=usergroups)).distinct()

        return qs

    def change_advice(self, user, grouplist=[]):
        logs = CredAudit.objects.filter(
            # Get a list of changes done
            Q(cred__group__in=grouplist, audittype=CredAudit.CREDCHANGE) |
            # Combined with a list of views from this user
            Q(cred__group__in=grouplist, audittype__in=[CredAudit.CREDVIEW, CredAudit.CREDPASSVIEW, CredAudit.CREDADD, CredAudit.CREDEXPORT], user=user)
        ).order_by('time', 'id')

        # Go through each entry in time order
        tochange = []
        for l in logs:
            # If this user viewed the password then change it
            if l.audittype in (CredAudit.CREDVIEW, CredAudit.CREDPASSVIEW, CredAudit.CREDADD, CredAudit.CREDEXPORT):
                tochange.append(l.cred.id)
            # If there was a change done not by this user, dont change it
            if l.audittype == CredAudit.CREDCHANGE and l.user != user:
                if l.cred.id in tochange:
                    tochange.remove(l.cred.id)

        # Fetch the list of credentials to change from the DB for the view
        return Cred.objects.filter(id__in=tochange)


class Cred(models.Model):
    METADATA = ('description', 'descriptionmarkdown', 'group', 'groups', 'tags', 'iconname', 'latest', 'id', 'modified', 'attachment_name', 'ssh_key_name')
    SORTABLES = ('title', 'username', 'group', 'id', 'modified')
    APP_SET = ('is_deleted', 'latest', 'modified', 'attachment_name', 'ssh_key_name')
    objects = SearchManager()

    # User changable fields
    title = models.CharField(verbose_name=_('Title'), max_length=64, db_index=True)
    itype = models.PositiveIntegerField(verbose_name=_('Type'), choices=CRED_TYPE, default=0 )
    url = models.URLField(verbose_name=_('URL'), blank=True, null=True, db_index=True)
    ip_addr = models.GenericIPAddressField(verbose_name=_('IP Address'), blank=True, null=True, db_index=True)
    ip_port = models.PositiveIntegerField(verbose_name=_('IP Port'), blank=True, null=True, db_index=True)
    username = models.CharField(verbose_name=_('Username'), max_length=250, blank=True, null=True, db_index=True)
    password = models.CharField(verbose_name=_('Password'), max_length=250, blank=True, null=True)
    descriptionmarkdown = models.BooleanField(verbose_name=_('Markdown Description'), default=False, )
    description = models.TextField(verbose_name=_('Description'), blank=True, null=True)
    group = models.ForeignKey(Group, verbose_name=_('Group'), on_delete=models.CASCADE)
    groups = models.ManyToManyField(Group, verbose_name=_('Groups'), related_name="child_creds", blank=True, default=None)
    tags = models.ManyToManyField(Tag, verbose_name=_('Tags'), related_name='child_creds', blank=True, default=None)
    iconname = models.CharField(verbose_name=_('Icon'), default='Key.png', max_length=64)
    ssh_key = SizedFileField(verbose_name=_('SSH key'), storage=CredAttachmentStorage(), max_upload_size=settings.RATTIC_MAX_ATTACHMENT_SIZE, null=True, blank=True, upload_to='not required')
    attachment = SizedFileField(verbose_name=_('Attachment'), storage=CredAttachmentStorage(), max_upload_size=settings.RATTIC_MAX_ATTACHMENT_SIZE, null=True, blank=True, upload_to='not required')

    # Application controlled fields
    is_deleted = models.BooleanField(default=False, db_index=True)
    latest = models.ForeignKey('Cred', related_name='history', blank=True, null=True, db_index=True, on_delete=models.CASCADE)
    modified = models.DateTimeField(db_index=True)
    created = models.DateTimeField(auto_now_add=True)

    ssh_key_name = models.CharField(max_length=64, null=True, blank=True)
    attachment_name = models.CharField(max_length=64, null=True, blank=True)

    def save(self, *args, **kwargs):
        try:
            # Get a copy of the old object from the db
            old = Cred.objects.get(id=self.id)

            # Reset the primary key so Django thinks its a new object
            old.id = None

            # Set the latest on the old copy to the new copy
            old.latest = self

            # Create it in the DB
            old.save()

            # Add the tags to the old copy now that it exists
            for t in self.tags.all():
                old.tags.add(t)

            # Add the groups
            for g in self.groups.all():
                old.groups.add(g)

            # Lets see what was changed
            oldcred = model_to_dict(old)
            newcred = model_to_dict(self)
            diff = DictDiffer(newcred, oldcred).changed()

            # Ohhhkaaay, so the attachment field looks like its changed every
            # time, so we do a deep comparison, if the files match we remove
            # it from the list of changed fields.
            for field in ('attachment', 'ssh_key'):
                if field_file_compare(oldcred[field], newcred[field]):
                    diff = diff - set((field, ))

            # Check if some non-metadata was changed
            chg = diff - set(Cred.METADATA)
            cred_changed = len(chg) > 0

            # If the creds were changed update the modify date
            if cred_changed:
                self.modified = now()
        except Cred.DoesNotExist:
            # This just means its new cred, set the initial modified time
            self.modified = now()

        super(Cred, self).save(*args, **kwargs)

    def delete(self):
        if not self.is_deleted:
            self.is_deleted = True
            self.save()
        else:
            super(Cred, self).delete()

    def on_changeq(self):
        return CredChangeQ.objects.filter(cred=self).exists()

    def is_latest(self):
        return self.latest is None

    def is_owned_by(self, user):
        # Staff can do anything
        if user.is_staff:
            return True

        # If its the latest and in your group you can see it
        if not self.is_deleted and self.latest is None and self.group in user.groups.all():
            return True

        # If the latest is in your group you can see it
        if not self.is_deleted and self.latest is not None and self.latest.group in user.groups.all():
            return True

        return False

    def is_visible_by(self, user):
        # Staff can see anything
        if user.is_staff:
            return True

        # If its the latest and (in your group or it belongs to a viewer group you also belong to) you can see it
        if not self.is_deleted and self.latest is None and (self.group in user.groups.all() or any([g in user.groups.all() for g in self.groups.all()])):
            return True

        # If the latest is in your group you can see it
        if not self.is_deleted and self.latest is not None and (self.latest.group in user.groups.all() or any([g in user.groups.all() for g in self.latest.groups.all()])):
            return True

        return False

    def ssh_key_fingerprint(self):
        return SSHKey(self.ssh_key.read(), self.password).fingerprint()

    def __unicode__(self):
        return self.title.encode('utf-8')


class CredAdmin(admin.ModelAdmin):
    list_display = ('title', 'username', 'group')


class CredAudit(models.Model):
    CREDADD = 'A'
    CREDCHANGE = 'C'
    CREDMETACHANGE = 'M'
    CREDVIEW = 'V'
    CREDEXPORT = 'X'
    CREDPASSVIEW = 'P'
    CREDDELETE = 'D'
    CREDSCHEDCHANGE = 'S'
    CREDLOGINTO = 'L'
    CREDAUDITCHOICES = (
        (CREDADD, _('Added')),
        (CREDCHANGE, _('Changed')),
        (CREDMETACHANGE, _('Only Metadata Changed')),
        (CREDVIEW, _('Only Details Viewed')),
        (CREDEXPORT, _('Exported')),
        (CREDDELETE, _('Deleted')),
        (CREDSCHEDCHANGE, _('Scheduled For Change')),
        (CREDPASSVIEW, _('Password Viewed')),
        (CREDLOGINTO, _('Login To')),
    )

    audittype = models.CharField(max_length=1, choices=CREDAUDITCHOICES)
    cred = models.ForeignKey(Cred, related_name='logs', on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='credlogs', on_delete=models.CASCADE)
    time = models.DateTimeField(auto_now_add=True)

    class Meta:
        get_latest_by = 'time'
        ordering = ('-time',)


class CredAuditAdmin(admin.ModelAdmin):
    list_display = ('audittype', 'user', 'cred', 'time')


class CredChangeQManager(models.Manager):
    def add_to_changeq(self, cred):
        return self.get_or_create(cred=cred)

    def for_user(self, user):
        return self.filter(cred__in=Cred.objects.visible(user))


class CredChangeQ(models.Model):

cred/templates/cred_detail.html
{% extends "base.html" %}
{% load i18n %}
{% load cred_markdown %}
{% load credicons %}

{% block title %}{{ cred.title }} - {% trans "Rattic" %}{% endblock %}

{% block headarea %}
<meta name="rattic_cred_id" content="{{ cred.id }}" />
{% endblock %}

{% block content %}
{% autoescape off %} 
<h1>{% cred_icon cred.iconname %} {{ cred.title }}</h1>
{% endautoescape %} 
{% if delete %}
<div class="alert alert-error">{% blocktrans %}You are about to delete this password. A staff member will be required if you want to undelete it.{% endblocktrans %}</div>
{% endif %}
{% if cred.is_deleted and cred.is_latest %}
<div class="alert alert-error">{% blocktrans %}This credential has been deleted and is in the trash can. It is only visible to staff. You can alter it if you wish, its history will still be recorded. Click the undelete button to restore it. If you click the Delete Permanently button then the password, its entire history and all its audit logs will be removed.{% endblocktrans %}</div>
{% endif %}
{% if not cred.is_latest %}
<div class="alert alert-info"><strong>{% trans "Hey there!" %}</strong> {% blocktrans %}This credential is an historical version.{% endblocktrans %} <a href="{% url 'cred:detail' cred.latest.id %}">{% trans "Click here" %}</a> {% blocktrans %}to see the latest version.{% endblocktrans %}</div>
{% endif %}
{% if cred.on_changeq and not readonly %}
<div class="alert alert-warning"><strong>{% trans "Change Required" %}</strong> {% blocktrans %}This credential is on the change queue and should have its password changed as soon as possible.{% endblocktrans %} {% trans "Why not" %} <a href="{% url 'cred:edit' cred.id %}">{% trans "do it now" %}</a>{% trans "?" %}</div>
{% endif %}
{% if cred.is_latest and not readonly %}
<div class="btn-group">
    <a class="btn" href="{% url 'cred:edit' cred.id %}">{% trans "Edit" %}</a>
    <a class="btn" href="{% url 'cred:list' 'history' cred.id 'ascending' 'id' %}">{% trans "History" %}</a>
    {% if not delete %}<a class="btn btn-danger" href="{% url 'cred:delete' cred.id %}">{% trans "Delete" %}</a>{% endif %}
    {% if not cred.is_deleted %}
        <a class="btn" href="{% url 'cred:addtoqueue' cred.id %}">{% trans "Add to Change Queue" %}</a>
    {% endif %}
    {% if cred.is_deleted and not undelete %}
    <a class="btn btn-success" href="{% url 'staff:credundelete' cred.id %}">{% trans "Undelete" %}</a>
    {% endif %}
</div>
<p></p>
{% endif %}
<table class="table table-striped table-bordered table-condensed">
{% if cred.url %}<tr><th>{% trans "URL" %}</th><td><a href="{{ cred.url }}">{{ cred.url }}</a></td></tr>{% endif %}
<tr>
  <th>{% trans "Username" %}</th>
  <td id="usertd" class="rattic-copy-button">
    {% if cred.username %}
      <span id="username">{{ cred.username }}</span>
      <button class="btn btn-mini" id="copyuser">{% trans "Copy" %}</button>
    {% endif %}
  </td>
</tr>
<tr>
  <th>
      {% trans "Password" %}
      <button class="btn btn-mini btn-password-show-hide btn-pass-fetchcred" data-target="#password"></button>
  </th>
  <td id="passtd" class="rattic-copy-button">
    <span id="password" class="passhidden">Fetching Password...</span>
    <button class="btn btn-mini" id="copyclipboard">{% trans "Copy" %}</button>
  </td>
</tr>

{% if cred.attachment %}
<tr><th>{% trans "Attachment" %}</th><td><a class="btn btn-mini" href="{% url "cred:downloadattachment" cred.id %}">{% trans "Download" %} {{ cred.attachment_name }}</a></td></tr>
{% endif %}
{% if cred.ssh_key %}
<tr><th>{% trans "SSH Key" %}</th><td><a class="btn btn-mini" href="{% url "cred:downloadsshkey" cred.id %}">{% trans "Download" %} {{ cred.ssh_key_fingerprint }}</a></td></tr>
{% endif %}

<tr><th>{% trans "Owner Group" %}</th><td>{% if cred.group in groups.all %}<a href="{% url 'cred:list' 'group' cred.group.id %}">{{ cred.group.name }}</a>{% else %}{{ cred.group.name }}{% endif %}</td></tr>
<tr><th>{% trans "Viewer Groups" %}</th>
    <td>
        {% for g in cred.groups.all %}
            {% if g in groups.all %}
                <a href="{% url 'cred:list' 'group' g.id %}">{{ g.name }}</a>
            {% else %}{{ g.name }}{% endif %}{% if not forloop.last %}, {% endif %}
        {% endfor %}
    </td>
 </tr>
<tr>
    <th>{% trans "Tags" %}</th>
    <td>{% for t in cred.tags.all %}
        <a href="{% url 'cred:list' 'tag' t.id %}">{{ t.name }}</a>
        {% if not forloop.last %}, {% endif %}
        {% endfor %}
    </td>
</tr>
<tr><th>{% trans "Last Changed" %}</th><td>{{ cred.modified }}</td></tr>
<tr><th>{% trans "Created" %}</th><td>{{ cred.created }}</td></tr>
</table>



<strong>{% trans "Description:" %}</strong>
{% if cred.descriptionmarkdown %}
  <div class="creddescription">
   {% autoescape off %}
   {% markdown_cred cred.description %}
   {% endautoescape %}
  </div>
{% else %}
  <pre>{{ cred.description }}</pre>
{% endif %}


{% if delete %}
    <form action="" method="post">{% csrf_token %}
        <input type="submit" class="btn btn-danger" value="{% trans "Delete" %}" />
    </form>
{% endif %}
{% if undelete %}
    <form action="" method="post">{% csrf_token %}
        <input type="submit" class="btn btn-success" value="{% trans "Undelete" %}" />
    </form>
{% endif %}
{% if not delete %}
    {% if credlogs %}
        {% include "credaudit_list.html" with type='user' %}
    {% endif %}
{% endif %}
{% endblock %}

cred/templates/cred_edit.html
{% extends "base.html" %}
{% load i18n %}
{% load credicons %}

{% block content %}

{% include "cred_part_passgenmodal.html" %}
{% include "cred_part_logomodal.html" with icons=icons txtfield='#id_iconname' imgfield='#logodisplay' %}

<h1>{% if not cred.id %}{% trans "Create Password" %}{% else %}{% trans "Edit Password" %}: {{ cred.title }}{% endif %}</h1>

<form class="form-horizontal" enctype="multipart/form-data" autocomplete="off" action="{{ action }}{% if next %}?next={{ next }}{% endif %}" method="post">{% csrf_token %}
    {% for field in form %}
        <div class="control-group">
            {{ field.errors }}
            <label class="control-label" for="{{ field.html_name }}">{{ field.label }}</label>
            <div class="controls">
              {{ field }}
            </div>
        </div>
    {% endfor %}
    <div class="controls">
        <input id="credsave" class="btn btn-primary" type="submit" value="{% trans "Submit" %}" />
    </div>
</form>
{% endblock %}

cred/templates/cred_part_export.html
{% load i18n %}

{% include "cred_part_passgenmodal.html" %}

<iframe name="hidden_iframe" class="hidden"></iframe>
<div id="exportmodal" class="modal hide fade">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3>{% trans "Export to Keepass" %}</h3>
  </div>
  <div class="modal-body">
    <p>{% blocktrans %}Please enter the password you would like the Keepass file to be encrypted with.{% endblocktrans %}</p>
    <form id="exportform" class="form-horizontal" target="hidden_iframe" action="{% url "cred:download" filter value  %}" method="post">{% csrf_token %}
        {% for field in exportform %}
            <div class="control-group">
                {{ field.errors }}
                <label class="control-label" for="{{ field.html_name }}">{{ field.label }}</label>
                <div class="controls">
                    {{ field }}
                </div>
            </div>
        {% endfor %}
    </form>
  </div>
  <div class="modal-footer">
    <a href="#" data-form="#exportform" data-input="#tagname" data-dismiss="modal" class="btn btn-primary rattic-form-submit-by-id">{% trans "Export" %}</a>
  </div>
</div>

cred/templates/cred_search.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}

<form class="text-center rattic-cred-search">
  <h1>Search</h1>
  <input id="search-box" type="search" name="box" class="search-query" placeholder="{% trans "Type your Query" %}">
  <input id="submit" type="submit" name="submit" class="btn btn-primary" value="{% trans "Search" %}">
</form>

{% endblock %}

cred/templates/cred_taglist.html
{% load i18n %}

{% include "cred_part_newtagmodal.html" %}

<table class="table table-striped table-bordered table-condensed">
<thead>
    <tr><td colspan="3"><a class="btn" data-toggle="modal" href="#newtagmodal" >{% trans "Add New" %}</a></td></tr>
    <tr><th>{% trans "Name" %}</th><th>{% trans "Count" %}</th><th>{% trans "Actions" %}</th></tr>
</thead>
<tbody>
    {% for t,c in tags.items %}
    <tr>
        <td><a href="{% url "cred:list" 'tag' t.id %}">{{ t.name }}</a></td>
        <td>{{ c }}</td>
        <td>
          <a href="{% url "cred:tagedit" t.id %}" class="btn btn-mini">{% trans "Rename" %}</a>
          <a href="{% url "cred:tagdelete" t.id %}" class="btn btn-mini">{% trans "Delete" %}</a>
        </td>
    </tr>
    {% endfor %}
</tbody>
</table>

cred/templates/credaudit_list.html
{% load i18n %}
<h2>{% trans "Audit Logs" %}</h2>
<table class="table table-striped table-bordered table-condensed">
<thead>
<tr>
    <th>{% trans "Action" %}</th>
    {% if type == 'user' %}
         <th>{% trans "User" %}</th>
    {% else %}
         <th>{% trans "Credential" %}</th>
    {% endif %}
    <th>{% trans "When" %}</th>
</tr>
</thead>
<tbody>
{% for audit in credlogs %}
<tr>
    <td>{{ audit.get_audittype_display }}</td>
    {% if type == 'user' %}
        <td><a href="{% url "staff:userdetail" audit.user.id %}">{{ audit.user.username }}</a></td>
    {% else %}
    <td><a href="{% url "cred:detail" audit.cred.id %}">{{ audit.cred.title }}</a></td>
    {% endif %}
    <td>{{ audit.time }}</td>
</tr>
{% endfor %}
</tbody>
<tr><td colspan="3"><a href="{{ morelink }}">{% trans "More logs..." %}</a></td></tr>
</table>